### ISSUE TITLE
TiKV panic on `commit_to()`

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/tikv#1084]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
`rustc 1.12.0-nightly (b30eff7ba 2016-08-05)`

2. What operating system and processor architecture are you using?
`Linux 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

3. What did you do?
I start 4 PD, 4 TiKV, and 4 TiDB, and keep running SQL on TiDB.
After a while, one of the TiKV panic.

4. What did you expect to see?
They keep running.

5. What did you see instead?
One of the TiKV panic.

See some logs here: [tikv.txt](https://github.com/pingcap/tikv/files/479754/tikv.txt)

**Comment by siddontang** [comment]
```
2016-09-19 17:02:10,420 peer.rs:1090 - INFO  - [region 265] 267 execute admin command cmd_type: ChangePeer change_peer {change_type: AddNode peer {id: 3890 store_id: 4}}
2016-09-19 17:02:10,420 peer.rs:1116 - WARN  - [region 265] 267 exec ConfChange "AddNode", epoch: conf_ver: 11 version: 23
2016-09-19 17:02:10,420 peer.rs:1149 - WARN  - [region 265] 267 add peer id: 3890 store_id: 4 to region id: 265 start_key: "t\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\001K\264\000\000\000\000\000\372" end_key: "t\200\000
\000\000\000\000\001\377k_r\200\000\000\000\000\377\001^L\000\000\000\000\000\372" region_epoch {conf_ver: 11 version: 23} peers {id: 267 store_id: 6} peers {id: 523 store_id: 5} peers {id: 636 store_id: 1}
2016-09-19 17:02:10,455 peer.rs:1090 - INFO  - [region 3692] 3693 execute admin command cmd_type: ChangePeer change_peer {change_type: RemoveNode peer {id: 3693 store_id: 6}}
2016-09-19 17:02:10,455 peer.rs:1116 - WARN  - [region 3692] 3693 exec ConfChange "RemoveNode", epoch: conf_ver: 16 version: 9
2016-09-19 17:02:10,455 peer.rs:1178 - WARN  - [region 3692] 3693 remove 3693 from region:id: 3692 start_key: "t\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001p\004\031\230\324\267\377\314\000\000\000\003\200\000\000\3
77\000\000\nV\003\000\000\000\374" end_key: "t\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001p\004\031\230\324\375\377\312\000\000\000\003\200\000\000\377\000\000\r\200\025\000\000\000\374" region_epoch {conf_ver: 16 v
ersion: 9} peers {id: 3693 store_id: 6} peers {id: 3694 store_id: 5} peers {id: 3695 store_id: 1} peers {id: 3892 store_id: 4}
2016-09-19 17:02:10,455 store.rs:659 - WARN  - [region 3692] destroy peer id: 3693 store_id: 6
2016-09-19 17:02:10,455 peer.rs:283 - INFO  - [region 3692] 3693 begin to destroy
2016-09-19 17:02:10,456 peer_storage.rs:486 - INFO  - [region 3692] 3693 clear peer 1 meta keys and 25 raft keys, takes Duration { secs: 0, nanos: 257349 }
2016-09-19 17:02:10,456 peer.rs:294 - INFO  - [region 3692] 3693 destroy itself, takes Duration { secs: 0, nanos: 408434 }
2016-09-19 17:02:10,456 region.rs:324 - INFO  - [region 3692] deleting data in [zt\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001p\004\031\230\324\267\377\314\000\000\000\003\200\000\000\377\000\000\nV\003\000\000\000\
374, zt\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001p\004\031\230\324\375\377\312\000\000\000\003\200\000\000\377\000\000\r\200\025\000\000\000\374)
2016-09-19 17:02:10,481 peer.rs:1090 - INFO  - [region 265] 267 execute admin command cmd_type: ChangePeer change_peer {change_type: RemoveNode peer {id: 267 store_id: 6}}
2016-09-19 17:02:10,481 peer.rs:1116 - WARN  - [region 265] 267 exec ConfChange "RemoveNode", epoch: conf_ver: 12 version: 23
2016-09-19 17:02:10,481 peer.rs:1178 - WARN  - [region 265] 267 remove 267 from region:id: 265 start_key: "t\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\001K\264\000\000\000\000\000\372" end_key: "t\200\000\000\000\000\000\
001\377k_r\200\000\000\000\000\377\001^L\000\000\000\000\000\372" region_epoch {conf_ver: 12 version: 23} peers {id: 267 store_id: 6} peers {id: 523 store_id: 5} peers {id: 636 store_id: 1} peers {id: 3890 store_id: 4}
2016-09-19 17:02:10,481 store.rs:659 - WARN  - [region 265] destroy peer id: 267 store_id: 6
2016-09-19 17:02:10,481 peer.rs:283 - INFO  - [region 265] 267 begin to destroy
2016-09-19 17:02:10,482 peer_storage.rs:486 - INFO  - [region 265] 267 clear peer 1 meta keys and 17 raft keys, takes Duration { secs: 0, nanos: 1327577 }
2016-09-19 17:02:10,482 peer.rs:294 - INFO  - [region 265] 267 destroy itself, takes Duration { secs: 0, nanos: 1480306 }
2016-09-19 17:02:10,482 region.rs:324 - INFO  - [region 265] deleting data in [zt\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\001K\264\000\000\000\000\000\372, zt\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\0
01^L\000\000\000\000\000\372)
2016-09-19 17:02:10,736 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:11,389 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:11,920 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:12,512 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:13,032 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:13,672 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:14,345 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:14,972 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:15,611 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:15,987 peer.rs:1090 - INFO  - [region 2553] 2555 execute admin command cmd_type: CompactLog compact_log {compact_index: 3044}
2016-09-19 17:02:15,987 compact.rs:97 - INFO  - [region 2553] compact 51 log entries
2016-09-19 17:02:16,112 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:16,912 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:17,412 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:18,140 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:18,732 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:19,374 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgHeartbeat to: 3233 from: 2507 term: 6 commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:19,393 peer.rs:1090 - INFO  - [region 3152] 3154 execute admin command cmd_type: ChangePeer change_peer {change_type: AddNode peer {id: 3894 store_id: 1}}
2016-09-19 17:02:19,393 peer.rs:1116 - WARN  - [region 3152] 3154 exec ConfChange "AddNode", epoch: conf_ver: 7 version: 9
2016-09-19 17:02:19,393 peer.rs:1149 - WARN  - [region 3152] 3154 add peer id: 3894 store_id: 1 to region id: 3152 start_key: "t\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001r\001\350\277\235\346\377\263\225\345\271\3
77\277\345\221\377\212\000\000\000\000\373\003\200\377\000\000\000\000\007\024E\000\376" end_key: "t\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001r\001\350\277\235\346\377\263\225\346\202\377\254\346\214\377\202\345\2
71\277\345\377\221\212\377\347\211\000\000\000\000\373\003\377\200\000\000\000\000\004\220\025\377\000\000\000\000\000\000\000\000\367" region_epoch {conf_ver: 7 version: 9} peers {id: 3153 store_id: 5} peers {id: 3154 store_id: 6} peers {id: 3155 store_id: 4}
2016-09-19 17:02:19,473 peer.rs:1090 - INFO  - [region 3152] 3154 execute admin command cmd_type: ChangePeer change_peer {change_type: RemoveNode peer {id: 3154 store_id: 6}}
2016-09-19 17:02:19,473 peer.rs:1116 - WARN  - [region 3152] 3154 exec ConfChange "RemoveNode", epoch: conf_ver: 8 version: 9
2016-09-19 17:02:19,473 peer.rs:1178 - WARN  - [region 3152] 3154 remove 3154 from region:id: 3152 start_key: "t\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001r\001\350\277\235\346\377\263\225\345\271\377\277\345\221\3
77\212\000\000\000\000\373\003\200\377\000\000\000\000\007\024E\000\376" end_key: "t\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001r\001\350\277\235\346\377\263\225\346\202\377\254\346\214\377\202\345\271\277\345\377\2
21\212\377\347\211\000\000\000\000\373\003\377\200\000\000\000\000\004\220\025\377\000\000\000\000\000\000\000\000\367" region_epoch {conf_ver: 8 version: 9} peers {id: 3153 store_id: 5} peers {id: 3154 store_id: 6} peers {id: 3155 store_
id: 4} peers {id: 3894 store_id: 1}
2016-09-19 17:02:19,473 store.rs:659 - WARN  - [region 3152] destroy peer id: 3154 store_id: 6
2016-09-19 17:02:19,473 peer.rs:283 - INFO  - [region 3152] 3154 begin to destroy
2016-09-19 17:02:19,473 peer_storage.rs:486 - INFO  - [region 3152] 3154 clear peer 1 meta keys and 12 raft keys, takes Duration { secs: 0, nanos: 86784 }
2016-09-19 17:02:19,473 peer.rs:294 - INFO  - [region 3152] 3154 destroy itself, takes Duration { secs: 0, nanos: 206826 }
2016-09-19 17:02:19,473 region.rs:324 - INFO  - [region 3152] deleting data in [zt\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001r\001\350\277\235\346\377\263\225\345\271\377\277\345\221\377\212\000\000\000\000\373\003
\200\377\000\000\000\000\007\024E\000\376, zt\200\000\000\000\000\000\001\377k_i\200\000\000\000\000\377\000\001r\001\350\277\235\346\377\263\225\346\202\377\254\346\214\377\202\345\271\277\345\377\221\212\377\347\211\000\000\000\000\373\
003\377\200\000\000\000\000\004\220\025\377\000\000\000\000\000\000\000\000\367)
2016-09-19 17:02:19,783 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgAppend to: 3233 from: 2507 term: 6 log_term: 6 index: 214 entries {entry_type: EntryConfChange term: 6 index: 215 data: \"\\020\\000\\030\\265\\036\\\"3\\n\\\"\\010\\311\\023\\022\\005\\010\\313\\023\\020\\
001\\\"\\020\\017\\260\\320&\\323\\036@I\\224\\262\\331\\223x\\255\\214q*\\004\\010\\r\\020\\020\\032\\r\\010\\001\\022\\t\\010\\000\\022\\005\\010\\265\\036\\020\\005\"} commit: 214} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:19,784 store.rs:1352 - ERROR - handle raft message err: Other(StringError("tombstone peer [epoch: conf_ver: 13 version: 16] receive an invalid message region_id: 2505 from_peer {id: 2507 store_id: 1} to_peer {id: 3233 sto
re_id: 6} message {msg_type: MsgAppend to: 3233 from: 2507 term: 6 log_term: 6 index: 215 commit: 215} region_epoch {conf_ver: 13 version: 16}, ignore it"))
2016-09-19 17:02:19,790 peer.rs:1090 - INFO  - [region 458] 460 execute admin command cmd_type: ChangePeer change_peer {change_type: AddNode peer {id: 3895 store_id: 5}}
2016-09-19 17:02:19,790 peer.rs:1116 - WARN  - [region 458] 460 exec ConfChange "AddNode", epoch: conf_ver: 11 version: 43
2016-09-19 17:02:19,790 peer.rs:1149 - WARN  - [region 458] 460 add peer id: 3895 store_id: 5 to region id: 458 start_key: "t\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\002\277\212\000\000\000\000\000\372" end_key: "t\200\
000\000\000\000\000\001\377k_r\200\000\000\000\000\377\002\322\"\000\000\000\000\000\372" region_epoch {conf_ver: 11 version: 43} peers {id: 459 store_id: 1} peers {id: 460 store_id: 6} peers {id: 2971 store_id: 4}
2016-09-19 17:02:19,809 peer.rs:206 - INFO  - [region 2505] replicate peer with id 3233                                                                                                                                              [20/5533]
2016-09-19 17:02:19,809 raft.rs:582 - INFO  - [region 2505] 3233 became follower at term 0
2016-09-19 17:02:19,809 raft.rs:265 - INFO  - [region 2505] 3233 newRaft [peers: [], term: 0, commit: 0, applied: 0, last_index: 0, last_term: 0]
2016-09-19 17:02:19,809 raft.rs:582 - INFO  - [region 2505] 3233 became follower at term 1
2016-09-19 17:02:19,809 raft.rs:728 - INFO  - [region 2505] 3233 [term: 1] received a MsgAppend message with higher term from 2507 [term: 6]
2016-09-19 17:02:19,810 raft.rs:582 - INFO  - [region 2505] 3233 became follower at term 6
2016-09-19 17:02:19,834 peer.rs:1090 - INFO  - [region 458] 460 execute admin command cmd_type: ChangePeer change_peer {change_type: RemoveNode peer {id: 460 store_id: 6}}
2016-09-19 17:02:19,834 peer.rs:1116 - WARN  - [region 458] 460 exec ConfChange "RemoveNode", epoch: conf_ver: 12 version: 43
2016-09-19 17:02:19,834 peer.rs:1178 - WARN  - [region 458] 460 remove 460 from region:id: 458 start_key: "t\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\002\277\212\000\000\000\000\000\372" end_key: "t\200\000\000\000\000\0
00\001\377k_r\200\000\000\000\000\377\002\322\"\000\000\000\000\000\372" region_epoch {conf_ver: 12 version: 43} peers {id: 459 store_id: 1} peers {id: 460 store_id: 6} peers {id: 2971 store_id: 4} peers {id: 3895 store_id: 5}
2016-09-19 17:02:19,834 store.rs:659 - WARN  - [region 458] destroy peer id: 460 store_id: 6
2016-09-19 17:02:19,834 peer.rs:283 - INFO  - [region 458] 460 begin to destroy
2016-09-19 17:02:19,835 peer_storage.rs:486 - INFO  - [region 458] 460 clear peer 1 meta keys and 15 raft keys, takes Duration { secs: 0, nanos: 1062348 }
2016-09-19 17:02:19,835 peer.rs:294 - INFO  - [region 458] 460 destroy itself, takes Duration { secs: 0, nanos: 1179023 }
2016-09-19 17:02:19,835 region.rs:324 - INFO  - [region 458] deleting data in [zt\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\377\002\277\212\000\000\000\000\000\372, zt\200\000\000\000\000\000\001\377k_r\200\000\000\000\000\37
7\002\322\"\000\000\000\000\000\372)
thread 'raftstore-6' panicked at 'to_commit 214 is out of range [last_index 0]', src/raft/raft_log.rs:197
stack backtrace:
   1:     0x7fdf6a6fc01d - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:     0x7fdf6a702071 - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:     0x7fdf6a700fe9 - std::panicking::default_hook::hbbe7fa36a995aca0
   4:     0x7fdf6a3dfcf0 - tikv::util::panic_hook::set_exit_hook::_{{closure}}::h02c2affb46e16f8b
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/util/panic_hook.rs:68
   5:     0x7fdf6a701627 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   6:     0x7fdf6a701512 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   7:     0x7fdf6a701440 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   8:     0x7fdf6a34f83a - _<tikv..raft..raft_log..RaftLog<T>>::commit_to::h7378bc46b016cf52
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raft/raft_log.rs:8
   9:     0x7fdf6a3579c8 - _<tikv..raft..raft..Raft<T>>::handle_heartbeat::h812bfb7a4d68aa73
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raft/raft.rs:1218
  10:     0x7fdf6a354e2e - _<tikv..raft..raft..Raft<T>>::step::hcac3677a88302183
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raft/raft.rs:1132
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raft/raft.rs:768
  11:     0x7fdf6a3853c0 - tikv::raftstore::store::peer::Peer::step::h68b94854f1bd018a
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raft/raw_node.rs:275
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raftstore/store/peer.rs:380
  12:     0x7fdf6a28feef - _<tikv..raftstore..store..store..Store<T, C> as mio..handler..Handler>::notify::h19494ad9211ccf95
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:427
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:1351
  13:     0x7fdf6a27a7b4 - _<tikv..raftstore..store..store..Store<T, C>>::run::h327b5221829aa8dc
                        at /home/huachaohuang/.cargo/git/checkouts/mio-e79f285e2377d154/master/src/event_loop.rs:366
                        at /home/huachaohuang/.cargo/git/checkouts/mio-e79f285e2377d154/master/src/event_loop.rs:313
                        at /home/huachaohuang/.cargo/git/checkouts/mio-e79f285e2377d154/master/src/event_loop.rs:261
                        at /home/huachaohuang/.go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:250
  14:     0x7fdf6a1ee36e - std::panicking::try::call::hac8448ebd42fa5ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:256
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:282
  15:     0x7fdf6a709b76 - __rust_maybe_catch_panic
  16:     0x7fdf6a25ef77 - _<F as alloc..boxed..FnBox<A>>::call_box::hc02734b785a6b0e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:312
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:587
  17:     0x7fdf6a6ff942 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  18:     0x7fdf68dfc183 - start_thread
  19:     0x7fdf6961637c - clone
  20:                0x0 - <unknown>

```

**Comment by huachaohuang** [comment]
More complete logs here [tikv.txt](https://github.com/pingcap/tikv/files/479833/tikv.txt).

**Comment by BusyJay** [comment]
Base on available logs, peer 3233 is destroyed accidentally, but it's still in the raft group. After the group do some conf change, the incoming heartbeat's epoch become valid to the peer. Hence the peer 3233 is recreated and then panic. But why and how was peer 3233 destroyed is still a mystery for lacking older logs.

**Comment by BusyJay** [comment]
This issue just happened again tonight. Consider following situation:

A region contains 2 peers A, B. A is leader. They decide to add a new peer C. Hence A will create a snapshot S asynchronously. In the meantime, they decide to remove peer C and add a new peer D on the same store as peer C. Then A picks up snapshot S and sends to D. D applies the snapshot and following entries such as removing C and adding D.

In our current implementation, when D tries to remove C, it will destroy itself for they have the same region id and store id. Hence D is deleted unexpectedly.

**Comment by siddontang** [comment]
Seem that PD removes the peer and then re-adds it in a short time?  /cc @huachaohuang 

But we still need to solve this condition. Maybe:
+ Check whether we can apply the snapshot or not.
+ Can't remove itself or panic if really meeting the invalid command.

**Comment by BusyJay** [comment]
The snapshot can be applied actually, the main problem is that D shouldn't remove itself when the log is just asking it to remove C.

On the other hand, because snapshot is generated asynchronously, there may be some cases that a stale snapshot is kept in memory. It will be an optimization to check if the snapshot is stale before actually sending it out.

**Comment by siddontang** [comment]
No, I don't think we can apply the snapshot. C and D are different peers, so D can't apply the snapshot sent to C before. We must ignore the snapshot, and we may not meet the following "remove C + add D" problem. 

If we meet the same problem "remove C + add D" again, we may meet another serious bug. 

We can check whether to send the snapshot or not, if peer id not mismatched, or any pending conf change exists, we may not send.
But if we have already sent the snapshot, how can we ignore this and tell the leader? 

/cc @xiang90 @ngaut

**Comment by siddontang** [comment]
Now we only check store id when removing + adding peer, but we should check peer it instead.

**Comment by BusyJay** [comment]
Snapshot data is not generated for some specified peer, there is no way to check who the snapshot was intended to sent to. All the peers should be able to apply it and following entries to reach the same state as leader's. This is the basic flow of raft state machine. If we meet another bug, there should be bugs in our apply implementation.
