### ISSUE TITLE
tikv-server: Segmentation fault

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1144]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e561e6b90b in je_tcache_bin_flush_small ()
(gdb) bt
#0  0x000055e561e6b90b in je_tcache_bin_flush_small ()
#1  0x000055e561e6c46b in je_tcache_event_hard ()
#2  0x000055e561e32214 in std::sync::mpsc::blocking::WaitToken::wait::h0c02dfee3186f6a9 ()
#3  0x000055e5617dc48c in recv<core::option::Option<tikv::server::coprocessor::endpoint::Task>> (self=0x7fdb1e419010,
    deadline=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sync/mpsc/shared.rs:237
#4  recv<core::option::Option<tikv::server::coprocessor::endpoint::Task>> (self=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sync/mpsc/mod.rs:884
#5  poll<tikv::server::coprocessor::endpoint::Host,tikv::server::coprocessor::endpoint::Task> (batch_size=50, runner=..., rx=..., counter=...)
    at /home/pingcap/tikv/src/util/worker/mod.rs:121
#6  {{closure}}<tikv::server::coprocessor::endpoint::Task,tikv::server::coprocessor::endpoint::Host> () at /home/pingcap/tikv/src/util/worker/mod.rs:173
#7  call_once<(),closure> (self=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:255
#8  std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
---Type <return> to continue, or q <return> to quit---j
#9  0x000055e561e425f7 in __rust_maybe_catch_panic ()
#10 0x000055e561858927 in try<(),std::panic::AssertUnwindSafe<closure>> (f=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
#11 catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
#12 {{closure}}<closure,()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:277
#13 alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7fdb18bea000, args=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
#14 0x000055e561e37ff1 in std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2 ()
#15 0x00007fdb306ec704 in ?? ()
#16 0x0000000000000000 in ?? ()
```

**Comment by siddontang** [comment]
Another coredump 
```
#0  0x00007fb3e37a990b in je_tcache_bin_flush_small ()
(gdb) bt
#0  0x00007fb3e37a990b in je_tcache_bin_flush_small ()
#1  0x00007fb3e37aa46b in je_tcache_event_hard ()
#2  0x00007fb3e3787901 in mallocx ()
#3  0x00007fb3e31a1bcf in allocate (size=16, align=1) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/heap.rs:59
#4  with_capacity<u8> (cap=16) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/raw_vec.rs:100
#5  with_capacity<u8> (capacity=16) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:331
#6  to_vec<u8> (s=&[u8](len: 16) = {...}) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/slice.rs:148
#7  to_vec<u8> (self=&[u8](len: 16) = {...}) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/slice.rs:1149
#8  call_command<tikv::server::transport::ServerRaftStoreRouter> (cb=..., self=<optimized out>, req=...)
    at /home/pingcap/tikv/src/storage/engine/raftkv.rs:135
#9  tikv::storage::engine::raftkv::{{impl}}::exec_requests<tikv::server::transport::ServerRaftStoreRouter> (self=0x7fb3d2218020, ctx=<optimized out>,
    reqs=..., cb=Box<FnBox<(core::result::Result<tikv::storage::engine::raftkv::CmdRes, tikv::storage::engine::Error>)>>)
    at /home/pingcap/tikv/src/storage/engine/raftkv.rs:161
#10 0x00007fb3e31c2318 in tikv::storage::engine::raftkv::{{impl}}::async_snapshot<tikv::server::transport::ServerRaftStoreRouter> (self=0x7fb3d2218020,
    ctx=0x7fb3aca2a870, cb=Box<FnBox<(core::result::Result<Box<Snapshot>, tikv::storage::engine::Error>)>>)
    at /home/pingcap/tikv/src/storage/engine/raftkv.rs:241
#11 0x00007fb3e32be84e in tikv::server::coprocessor::endpoint::{{impl}}::run_batch (self=<optimized out>, tasks=<optimized out>)
    at /home/pingcap/tikv/src/server/coprocessor/endpoint.rs:149
---Type <return> to continue, or q <return> to quit---
#12 0x00007fb3e311a5e9 in poll<tikv::server::coprocessor::endpoint::Host,tikv::server::coprocessor::endpoint::Task> (batch_size=50, runner=..., rx=...,
    counter=...) at /home/pingcap/tikv/src/util/worker/mod.rs:137
#13 {{closure}}<tikv::server::coprocessor::endpoint::Task,tikv::server::coprocessor::endpoint::Host> () at /home/pingcap/tikv/src/util/worker/mod.rs:173
#14 call_once<(),closure> (self=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:255
#15 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
#16 0x00007fb3e37805f7 in __rust_maybe_catch_panic ()
#17 0x00007fb3e3196927 in try<(),std::panic::AssertUnwindSafe<closure>> (f=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
#18 catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
#19 {{closure}}<closure,()> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:277
#20 alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7fb3d2222000, args=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
#21 0x00007fb3e3775ff1 in std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2 ()
#22 0x00007fb3e29a9704 in ?? ()
#23 0x0000000000000000 in ?? ()
```

**Comment by siddontang** [comment]
Another coredump
```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa82c551c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56     	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)
(gdb) bt
#0  0x00007fa82c551c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa82c555028 in __GI_abort () at abort.c:89
#2  0x00007fa82c58e2a4 in __libc_message (do_abort=do_abort@entry=1,
    fmt=fmt@entry=0x7fa82c69c6b0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fa82c59a55e in malloc_printerr (ptr=<optimized out>,
    str=0x7fa82c698801 "free(): invalid pointer", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fa82d40f31f in deallocate (ptr=<optimized out>, old_size=<optimized out>,
    align=1)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/heap.rs:113
#6  drop<u8> (self=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc---Type <return> to continue, or q <return> to quit---
/raw_vec.rs:560
#7  tikv::server::coprocessor::endpoint::{{impl}}::run_batch (self=<optimized out>,
    tasks=<optimized out>) at /home/jay/tikv/src/server/coprocessor/endpoint.rs:131
#8  0x00007fa82d271fe9 in poll<tikv::server::coprocessor::endpoint::Host,tikv::server::coprocessor::endpoint::Task> (batch_size=50, runner=..., rx=..., counter=...)
    at /home/jay/tikv/src/util/worker/mod.rs:137
#9  {{closure}}<tikv::server::coprocessor::endpoint::Task,tikv::server::coprocessor::endpoint::Host> () at /home/jay/tikv/src/util/worker/mod.rs:173
#10 call_once<(),closure> (self=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:255
#11 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (
    data=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
---Type <return> to continue, or q <return> to quit---
#12 0x00007fa82d8d64e7 in __rust_maybe_catch_panic ()
#13 0x00007fa82d2e3697 in try<(),std::panic::AssertUnwindSafe<closure>> (f=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
#14 catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=...)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
#15 {{closure}}<closure,()> ()
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/mod.rs:277
#16 alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7fa7cc0c99a0,
    args=<optimized out>)
    at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:595
#17 0x00007fa82d8cbee1 in std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
---Type <return> to continue, or q <return> to quit---
    ()
#18 0x00007fa82cafe184 in start_thread (arg=0x7fa8065f2700) at pthread_create.c:312
#19 0x00007fa82c61537d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by BusyJay** [comment]
We need a demo project (or some snippets) to reproduce the issue conveniently.
