### ISSUE TITLE
testcase util::fs::tests::test_get_disk_stat fails on CircleCI

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1318]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
nightly-2016-10-06

2. What operating system and processor architecture are you using?
Linux, x86_64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

    cargo test

4. What did you expect to see?

test passed
5. What did you see instead?

```
thread 'util::fs::tests::test_get_disk_stat' panicked at 'available not changed after 100 tries.', src/util/fs.rs:76
stack backtrace:
   1:     0x7fb0446c453f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x7fb0446ca19d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x7fb0446c8a9a - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x7fb043e44e23 - tikv::util::panic_hook::track_hook::{{closure}}::hb837f2406673f204
                        at /home/ubuntu/tikv/src/util/panic_hook.rs:61
   5:     0x7fb043a2232f - <std::thread::local::LocalKey<T>>::with::h9083fb0650d0ba17
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
   6:     0x7fb043c2fd72 - tikv::util::panic_hook::track_hook::hf105ca85dc179673
                        at /home/ubuntu/tikv/src/util/panic_hook.rs:55
   7:     0x7fb043e50563 - core::ops::Fn::call::hca09d741884900a1
   8:     0x7fb0446c9065 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   9:     0x7fb0446c8f32 - std::panicking::begin_panic::hf6c488cee66e7f17
  10:     0x7fb0446c8e70 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
  11:     0x7fb043cda7eb - tikv::util::fs::tests::test_get_disk_stat::h4066261b924b08d8
                        at /home/ubuntu/tikv/src/util/fs.rs:76
  12:     0x7fb043e9ba2b - <F as alloc::boxed::FnBox<A>>::call_box::hdb02e989a089cf4e
  13:     0x7fb043e95ad7 - std::panicking::try::do_call::hb5542e7f62c71bb7
  14:     0x7fb0446d1c66 - __rust_maybe_catch_panic
  15:     0x7fb043e9b899 - <F as alloc::boxed::FnBox<A>>::call_box::hb415bac963aa88f8
  16:     0x7fb0446c7610 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  17:     0x7fb042503183 - start_thread
  18:     0x7fb042d1d37c - clone
  19:                0x0 - <unknown>
FAILED
```

It uses Xen Virtual block Device and btrfs.
mount option is : `` (rw,nodev,noatime,nodatasum,nodatacow,ssd,space_cache) ``
the ``.available`` value never changes after generating 100 files.
BTW, creating files of 1000 bytes is weird, better make it 1024 to align on block boundary.

The underlying problem maybe some NFS lies about ``statfs()``.

**Comment by andelf** [comment]
And test case shouldn't panic!() instead of assert_eq!()

**Comment by siddontang** [comment]
@andelf 

Can the test pass now?
