### ISSUE TITLE
tests:test_validate_endpoints  failed sometime in CI.

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1726]
Hi,  all,
   `pd::test_rpc_client::test_validate_endpoints` would panicked some time with the following details:

```
test pd::test_rpc_client::test_validate_endpoints ... thread 'grpc-server-loop' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address already in use" } }', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
   1: httpbis::server::run_server_event_loop
             at /home/ubuntu/.cargo/git/checkouts/grpc-rust-c0d13ba76cd4c520/13bdc72/http2/src/server.rs:117
   2: httpbis::server::HttpServer::new::{{closure}}
             at /home/ubuntu/.cargo/git/checkouts/grpc-rust-c0d13ba76cd4c520/13bdc72/http2/src/server.rs:183
   3: <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once
             at /checkout/src/libstd/panic.rs:296
   4: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
   5: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   6: std::panicking::try
             at /checkout/src/libstd/panicking.rs:433
   7: std::panic::catch_unwind
             at /checkout/src/libstd/panic.rs:361
   8: std::thread::Builder::spawn::{{closure}}
             at /checkout/src/libstd/thread/mod.rs:360
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:640
  10: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  11: start_thread
  12: clone
thread 'pd::test_rpc_client::test_validate_endpoints' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
   1: httpbis::server::HttpServer::new
             at /home/ubuntu/.cargo/git/checkouts/grpc-rust-c0d13ba76cd4c520/13bdc72/http2/src/server.rs:187
   2: grpc::server::GrpcServer::new
             at /home/ubuntu/.cargo/git/checkouts/grpc-rust-c0d13ba76cd4c520/13bdc72/src/server.rs:287
   3: kvproto::pdpb_grpc::PDAsyncServer::new
             at /home/ubuntu/.cargo/git/checkouts/kvproto-e694950bee90bc86/5e57c99/src/pdpb_grpc.rs:490
   4: tests::pd::mock::server::Server::run
             at ./tests/pd/mock/server.rs:43
   5: tests::pd::test_rpc_client::test_validate_endpoints
             at ./tests/pd/test_rpc_client.rs:108
   6: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1368
             at /checkout/src/libcore/ops.rs:2606
             at /checkout/src/libtest/lib.rs:140
   7: std::panicking::try::do_call
             at /checkout/src/libtest/lib.rs:1314
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   9: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libtest/lib.rs:1313
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/thread/mod.rs:360
             at /checkout/src/liballoc/boxed.rs:640
  12: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  13: start_thread
  14: clone
FAILED
```

@disksing @BusyJay @overvenus PTAL.

**Comment by overvenus** [comment]
The error message is `Address already in use`, has been fix in #1935. I am closing it now.
