### ISSUE TITLE
tests:test_server_apply_new_version_snapshot failed

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1744]
Hi,all, 
`test_server_apply_new_version_snapshot` failed in  CI [https://circleci.com/gh/pingcap/tikv/1620?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link](https://circleci.com/gh/pingcap/tikv/1620?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), here is the detail:
```
est raftstore::test_split_region::test_server_apply_new_version_snapshot ... thread 'raftstore::test_split_region::test_server_apply_new_version_snapshot' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for Duration { secs: 5, nanos: 0 }")', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: tikv::util::panic_hook::track_hook::{{closure}}
             at ./src/util/panic_hook.rs:61
   1: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:253
   2: tikv::util::panic_hook::track_hook
             at ./src/util/panic_hook.rs:55
   3: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2511
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:550
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: <tests::raftstore::cluster::Cluster<T>>::query_leader
             at ./tests/raftstore/cluster.rs:249
  12: <tests::raftstore::cluster::Cluster<T>>::leader_of_region
             at ./tests/raftstore/cluster.rs:286
  13: <tests::raftstore::cluster::Cluster<T>>::call_command_on_leader
             at ./tests/raftstore/cluster.rs:210
  14: <tests::raftstore::cluster::Cluster<T>>::request
             at ./tests/raftstore/cluster.rs:446
  15: <tests::raftstore::cluster::Cluster<T>>::must_put_cf
             at ./tests/raftstore/cluster.rs:520
  16: <tests::raftstore::cluster::Cluster<T>>::must_put
             at ./tests/raftstore/cluster.rs:516
  17: tests::raftstore::test_split_region::test_apply_new_version_snapshot
             at ./tests/raftstore/test_split_region.rs:350
  18: tests::raftstore::test_split_region::test_server_apply_new_version_snapshot
             at ./tests/raftstore/test_split_region.rs:387
  19: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1368
             at /checkout/src/libcore/ops.rs:2606
             at /checkout/src/libtest/lib.rs:140
  20: std::panicking::try::do_call
             at /checkout/src/libtest/lib.rs:1314
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
  21: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  22: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libtest/lib.rs:1313
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  24: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/thread/mod.rs:360
             at /checkout/src/liballoc/boxed.rs:640
  25: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  26: start_thread
  27: clone
FAILED
```

@BusyJay PTAL.

**Comment by siddontang** [comment]
do we fix it now? @AndreMouche

**Comment by AndreMouche** [comment]
not yet @siddontang

**Comment by AndreMouche** [comment]
It failed again recently https://circleci.com/gh/pingcap/tikv/4004?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
