### ISSUE TITLE
tests:test_server_compact_lock_cf failed 

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1881]
Hi,
   `test_server_compact_lock_cf`  randomly failed on my machine with the following details:

```
thread 'raftstore::test_compact_lock_cf::test_server_compact_lock_cf' panicked at 'assertion failed: compact_write_bytes > 0', tests/raftstore/test_compact_lock_cf.rs:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:265
   6: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   7: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2588
   8: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:550
   9: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
  10: tests::raftstore::test_compact_lock_cf::flush_then_check
             at tests/raftstore/test_compact_lock_cf.rs:33
  11: tests::raftstore::test_compact_lock_cf::test_compact_lock_cf
             at tests/raftstore/test_compact_lock_cf.rs:60
  12: tests::raftstore::test_compact_lock_cf::test_server_compact_lock_cf
             at tests/raftstore/test_compact_lock_cf.rs:67
  13: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1451
             at /checkout/src/libcore/ops.rs:2683
             at /checkout/src/libtest/lib.rs:140
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
test raftstore::test_compact_lock_cf::test_server_compact_lock_cf ... FAILED
```

 It seems caused by the operation `sleep` https://github.com/pingcap/tikv/blob/master/tests/raftstore/test_compact_lock_cf.rs#L28.
Is it possible to  use `channel` instead of the `sleep`?

**Comment by siddontang** [comment]
Do we fix it now? @zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
Yes

**Comment by BusyJay** [comment]
But [it](https://travis-ci.org/pingcap/tikv/jobs/250306021) still fails.
