### ISSUE TITLE
tests: test_server_split_region_diff_check failed.

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1905]
Hi,
   [`test_split_region::test_server_split_region_diff_check ` ](https://github.com/pingcap/tikv/blob/master/tests/raftstore/test_split_region.rs#L527)randomly failed on CI.  Here is the [failed detail](https://travis-ci.org/pingcap/tikv/jobs/240669291):

```
hread 'raftstore::test_split_region::test_server_split_region_diff_check' panicked at 'expect split cnt 20, but got 19', tests/raftstore/test_split_region.rs:519
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:265
   6: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   7: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2588
   8: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:550
   9: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
  10: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
  11: tests::raftstore::test_split_region::test_split_region_diff_check
             at tests/raftstore/test_split_region.rs:519
  12: tests::raftstore::test_split_region::test_server_split_region_diff_check
             at tests/raftstore/test_split_region.rs:530
  13: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1451
             at /checkout/src/libcore/ops.rs:2683
             at /checkout/src/libtest/lib.rs:140
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
test raftstore::test_split_region::test_server_split_region_diff_check ... FAILED
```

@BusyJay @zhangjinpeng1987 @hhkbp2  PTAL

**Comment by BusyJay** [comment]
From the log, pd doesn't respond anything to `ask_split` split request.

**Comment by siddontang** [comment]
PTAL @overvenus
