### ISSUE TITLE
tests: test_node_read_leader_with_unapplied_log failed

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1920]
Hi, `test_node_read_leader_with_unapplied_log ` failed randomly on the CI with the following details(https://travis-ci.org/pingcap/tikv/jobs/241465219):

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:265
   6: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   7: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2588
   8: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:550
   9: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
  10: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
  11: tests::raftstore::test_multi::test_read_leader_with_unapplied_log
             at tests/raftstore/test_multi.rs:526
  12: tests::raftstore::test_multi::test_node_read_leader_with_unapplied_log
             at tests/raftstore/test_multi.rs:539
  13: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1451
             at /checkout/src/libcore/ops.rs:2683
             at /checkout/src/libtest/lib.rs:140
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
test raftstore::test_multi::test_node_read_leader_with_unapplied_log ... FAILED
```

@BusyJay PTAL.

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987

**Comment by AndreMouche** [comment]
The test failed again with the following details(https://travis-ci.org/pingcap/tikv/jobs/256855636):
```
thread 'raftstore::test_multi::test_node_read_leader_with_unapplied_log' panicked at 'read should be dropped immediately, but got header {current_term: 9} responses {cmd_type: Get get {value: "v"}}', tests/raftstore/test_multi.rs:526
```
