### ISSUE TITLE
tests: test_node_stale_snap failed

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1922]
hi, 
    `test_node_stale_snap` failed randomly on CI with the following details(https://travis-ci.org/pingcap/tikv/jobs/241943046):

```
thread 'raftstore::test_snap::test_node_stale_snap' panicked at 'can't get value Some("v3") for key "k3"', tests/raftstore/util.rs:55
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:265
   6: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   7: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2588
   8: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:550
   9: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
  10: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
  11: tests::raftstore::util::must_get
             at tests/raftstore/util.rs:55
  12: tests::raftstore::util::must_get_equal
             at tests/raftstore/util.rs:61
  13: tests::raftstore::test_snap::test_node_stale_snap
             at tests/raftstore/test_snap.rs:368
  14: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1451
             at /checkout/src/libcore/ops.rs:2683
             at /checkout/src/libtest/lib.rs:140
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
test raftstore::test_snap::test_node_stale_snap ... FAILED
```
@hhkbp2 @BusyJay PTAL

**Comment by BusyJay** [comment]
From the log, we can tell that apply thread got stuck after [registering applying state](https://github.com/pingcap/tikv/blob/master/src/raftstore/store/worker/region.rs#L197) for at lease 10 secs.

Log: [test_node_stale_snap.txt](https://github.com/pingcap/tikv/files/1090626/test_node_stale_snap.txt)

**Comment by hhkbp2** [comment]
@BusyJay 
It could be seen in the log
```
4374:2017/06/20 12:19:41.043 snap.rs:2244: [DEBUG] register [key: 1_6_13, entry: Applying]

... blocking due to snapshot applying

2017/06/20 12:19:52.261 snap.rs:2263: [DEBUG] deregister [key: 1_6_13, entry: Applying]
2017/06/20 12:19:52.261 region.rs:234: [WARN] applying snapshot for region 1 is aborted.
2017/06/20 12:19:52.261 mod.rs:74: [WARN] handle task Snap apply for 1 [takes Duration { secs: 11, nanos: 218478733 }]

...
```
`peer(3, 4)` entered the apply function
https://github.com/pingcap/tikv/blob/master/src/raftstore/store/snap.rs#L1320
but it took a long time like 10 second to react with the `node::stop() -> abort state`. In this part of code, there is no locking involved, but only RocksDB operations. And since `peer(3, 4)` didn't involve any snapshot operation(seen in the logs). And also it finally reacted with long delay. It's not a dead lock or locking issue there.
No more info of what happened during to this time phase. It's not likely that the writing to RocksDB would take such a long time. But it seemed to be so, which turns to an dead end to me.

I suggest we add one log for apply each sst cf file, so that we have a closer info of that it's hanging on applying which cf, if it happens later. It will not be direct info to the solution though. @siddontang
