### ISSUE TITLE
tests: test_node_apply_new_version_snapshot failed

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1924]
hi, 
`test_node_apply_new_version_snapshot ` failed randomly on the CI with the following detailes(https://travis-ci.org/pingcap/tikv/jobs/241986570):

```
thread 'raftstore::test_split_region::test_node_apply_new_version_snapshot' panicked at 'can't get value Some("v1") for key "k1"', tests/raftstore/util.rs:55
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:265
   6: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   7: core::ops::Fn::call
             at /checkout/src/libcore/ops.rs:2588
   8: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:550
   9: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
  10: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
  11: tests::raftstore::util::must_get
             at tests/raftstore/util.rs:55
  12: tests::raftstore::util::must_get_equal
             at tests/raftstore/util.rs:61
  13: tests::raftstore::test_split_region::test_apply_new_version_snapshot
             at tests/raftstore/test_split_region.rs:394
  14: tests::raftstore::test_split_region::test_node_apply_new_version_snapshot
             at tests/raftstore/test_split_region.rs:401
  15: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1451
             at /checkout/src/libcore/ops.rs:2683
             at /checkout/src/libtest/lib.rs:140
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
test raftstore::test_split_region::test_node_apply_new_version_snapshot ... FAILED
```

@zhangjinpeng1987 @hhkbp2 @BusyJay PTAL

**Comment by BusyJay** [comment]
From the log, the generating snapshot thread hangs for a long time. Maybe related to #1922.

**Comment by hhkbp2** [comment]
Seen from the log:

After 2 became leader and the net filter to  store 3 is cleared, a snapshot is requested but didn't finished generation:

```
2017/06/12 11:57:20.381 peer_storage.rs:511: [INFO] [region 1] 2 requesting snapshot...
2017/06/12 11:57:20.381 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.383 peer_storage.rs:849: [DEBUG] [region 1] begin to generate a snapshot
2017/06/12 11:57:20.384 snap.rs:1194: [INFO] [region 1] scan snapshot /tmp/test_cluster.kxl9uTVnpSEa/gen_1_7_12_(default|lock|write).sst, cf default, key count 1, size 5
2017/06/12 11:57:20.385 snap.rs:1194: [INFO] [region 1] scan snapshot /tmp/test_cluster.kxl9uTVnpSEa/gen_1_7_12_(default|lock|write).sst, cf lock, key count 0, size 0
2017/06/12 11:57:20.385 snap.rs:1194: [INFO] [region 1] scan snapshot /tmp/test_cluster.kxl9uTVnpSEa/gen_1_7_12_(default|lock|write).sst, cf write, key count 0, size 0
2017/06/12 11:57:20.388 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.400 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.425 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.451 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.479 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.498 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.517 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
2017/06/12 11:57:20.541 raft.rs:439: [DEBUG] [region 1] 2 failed to send snapshot to 3 because snapshot is termporarily unavailable
```

There should be log message in 
https://github.com/pingcap/tikv/blob/master/src/raftstore/store/snap.rs#L1232
if the generation was successfully done. Or 
https://github.com/pingcap/tikv/blob/master/src/raftstore/store/worker/region.rs#L115
if it failed.

Neither are seen in the log, the only possible reason is that it hangs somewhere after it successfully scan sst files before the whole process is done. But the code involved here only related to file operations, but no locking.
https://github.com/pingcap/tikv/blob/master/src/raftstore/store/snap.rs#L1202
(from line 1202 - 1239)

Odd. No clue for that.
