### ISSUE TITLE
Leak sanitizer check fails

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1978]
```
failures:

---- util::buf::tests::test_shrink_to stdout ----
	thread 'util::buf::tests::test_shrink_to' panicked at 'assertion failed: `(left == right)`
  left: `PipeBuffer [start: 0, end: 1, buf: \000\001]`,
 right: `[1]`', src/util/buf.rs:493
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    util::buf::tests::test_shrink_to

test result: FAILED. 309 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

```

```
==1026==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 192 byte(s) in 3 object(s) allocated from:
    #0 0x558f03a0dc3f in __interceptor_malloc /checkout/src/compiler-rt/lib/lsan/lsan_interceptors.cc:56 (discriminator 2)
    #1 0x558f03a0dc3f in ?? ??:0
    #2 0x558f039d3adc in alloc::heap::allocate /checkout/src/liballoc/heap.rs:136
    #3 0x558f039d3adc in ?? ??:0
    #4 0x558f039d3a5d in alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:231
    #5 0x558f039d3a5d in ?? ??:0
    #6 0x558f039d6be6 in alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:243
    #7 0x558f039d6be6 in mio::poll::{{impl}}::new2 /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:1388
    #8 0x558f039d6be6 in ?? ??:0
    #9 0x558f0385340a in tokio_core::reactor::{{impl}}::spawn /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:555
    #10 0x558f0385340a in ?? ??:0
    #11 0x558f02853f2d in tokio_core::reactor::{{impl}}::spawn<futures::future::map_err::MapErr<tokio_timer::timer::Sleep, closure>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:686
    #12 0x558f02853f2d in ?? ??:0
    #13 0x558f02f1cfd2 in tikv::util::worker::future::test::{{impl}}::run /home/pingcap/workspace/tikv/src/util/worker/future.rs:178
    #14 0x558f02f1cfd2 in ?? ??:0
    #15 0x558f02f1bb35 in tikv::util::worker::future::poll::{{closure}}<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:81
    #16 0x558f02f1bb35 in ?? ??:0
    #17 0x558f0284268d in futures::stream::for_each::{{impl}}::poll<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>,closure,core::result::Result<(), ()>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/stream/for_each.rs:46
    #18 0x558f0284268d in ?? ??:0
    #19 0x558f02e656ac in futures::task_impl::std::{{impl}}::poll_future::{{closure}}<futures::stream::for_each::ForEach<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>, closure, core::result::Result<(), ()>>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/task_impl/std/mod.rs:242
    #20 0x558f02e656ac in ?? ??:0
    #21 0x558f0299620f in futures::task_impl::{{impl}}::enter::{{closure}}<futures::stream::for_each::ForEach<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>, closure, core::result::Result<(), ()>>,closure,core::result::Result<futures::poll::Async<()>, ()>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/task_impl/mod.rs:352
    #22 0x558f0299620f in ?? ??:0
    #23 0x558f02e65353 in futures::task_impl::std::set<closure,core::result::Result<futures::poll::Async<()>, ()>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/task_impl/std/mod.rs:90
    #24 0x558f02e65353 in ?? ??:0
    #25 0x558f02995fa9 in futures::task_impl::{{impl}}::enter<futures::stream::for_each::ForEach<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>, closure, core::result::Result<(), ()>>,closure,core::result::Result<futures::poll::Async<()>, ()>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/task_impl/mod.rs:352
    #26 0x558f02995fa9 in ?? ??:0
    #27 0x558f02e65632 in futures::task_impl::std::{{impl}}::poll_future<futures::stream::for_each::ForEach<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>, closure, core::result::Result<(), ()>>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/task_impl/std/mod.rs:242
    #28 0x558f02e65632 in ?? ??:0
    #29 0x558f02853ade in tokio_core::reactor::{{impl}}::run::{{closure}}<futures::stream::for_each::ForEach<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>, closure, core::result::Result<(), ()>>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:243
    #30 0x558f02853ade in ?? ??:0
    #31 0x558f02925c6c in scoped_tls::{{impl}}::set<tokio_core::reactor::Core,closure,core::result::Result<futures::poll::Async<()>, ()>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
    #32 0x558f02925c6c in ?? ??:0
    #33 0x558f02853929 in tokio_core::reactor::{{impl}}::run<futures::stream::for_each::ForEach<futures::stream::take_while::TakeWhile<futures::sync::mpsc::UnboundedReceiver<core::option::Option<u64>>, closure, core::result::Result<bool, ()>>, closure, core::result::Result<(), ()>>> /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:242
    #34 0x558f02853929 in ?? ??:0
    #35 0x558f02f1b98c in tikv::util::worker::future::poll<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:85
    #36 0x558f02f1b98c in ?? ??:0
    #37 0x558f03208c0e in tikv::util::worker::future::{{impl}}::start::{{closure}}<u64,tikv::util::worker::future::test::StepRunner> /home/pingcap/workspace/tikv/src/util/worker/future.rs:115
    #38 0x558f03208c0e in ?? ??:0
    #39 0x558f0292e912 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> /checkout/src/libstd/sys_common/backtrace.rs:136
    #40 0x558f0292e912 in ?? ??:0
    #41 0x558f02964dba in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:364
    #42 0x558f02964dba in ?? ??:0
    #43 0x558f02839e52 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296
    #44 0x558f02839e52 in ?? ??:0
    #45 0x558f02969272 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:454
    #46 0x558f02969272 in ?? ??:0
    #47 0x558f03ea1dcc in panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98
    #48 0x558f03ea1dcc in ?? ??:0
    #49 0x558f02967475 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:433
    #50 0x558f02967475 in ?? ??:0
    #51 0x558f02956e39 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361
    #52 0x558f02956e39 in ?? ??:0
    #53 0x558f02962581 in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:363
    #54 0x558f02962581 in ?? ??:0
    #55 0x558f02c524a7 in alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:652
    #56 0x558f02c524a7 in ?? ??:0
    #57 0x558f03e995db in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:662
    #58 0x558f03e995db in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21
    #59 0x558f03e995db in std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84
    #60 0x558f03e995db in ?? ??:0
    #61 0x7f97f6f616b9 in start_thread ??:?
    #62 0x7f97f6f616b9 in ?? ??:0

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x558f03a0dc3f in __interceptor_malloc /checkout/src/compiler-rt/lib/lsan/lsan_interceptors.cc:56 (discriminator 2)
    #1 0x558f03a0dc3f in ?? ??:0
    #2 0x558f039d3adc in alloc::heap::allocate /checkout/src/liballoc/heap.rs:136
    #3 0x558f039d3adc in ?? ??:0
    #4 0x558f039d3a5d in alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:231
    #5 0x558f039d3a5d in ?? ??:0
    #6 0x558f039d8098 in alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:243
    #7 0x558f039d8098 in mio::poll::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:1869
    #8 0x558f039d8098 in ?? ??:0
    #9 0x558f039d54d2 in mio::poll::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:617
    #10 0x558f039d54d2 in ?? ??:0
    #11 0x558f0384cc8a in tokio_core::reactor::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:157
    #12 0x558f0384cc8a in ?? ??:0
    #13 0x558f02f1b862 in tikv::util::worker::future::poll<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:77
    #14 0x558f02f1b862 in ?? ??:0
    #15 0x558f03208c0e in tikv::util::worker::future::{{impl}}::start::{{closure}}<u64,tikv::util::worker::future::test::StepRunner> /home/pingcap/workspace/tikv/src/util/worker/future.rs:115
    #16 0x558f03208c0e in ?? ??:0
    #17 0x558f0292e912 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> /checkout/src/libstd/sys_common/backtrace.rs:136
    #18 0x558f0292e912 in ?? ??:0
    #19 0x558f02964dba in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:364
    #20 0x558f02964dba in ?? ??:0
    #21 0x558f02839e52 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296
    #22 0x558f02839e52 in ?? ??:0
    #23 0x558f02969272 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:454
    #24 0x558f02969272 in ?? ??:0
    #25 0x558f03ea1dcc in panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98
    #26 0x558f03ea1dcc in ?? ??:0
    #27 0x558f02967475 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:433
    #28 0x558f02967475 in ?? ??:0
    #29 0x558f02956e39 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361
    #30 0x558f02956e39 in ?? ??:0
    #31 0x558f02962581 in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:363
    #32 0x558f02962581 in ?? ??:0
    #33 0x558f02c524a7 in alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:652
    #34 0x558f02c524a7 in ?? ??:0
    #35 0x558f03e995db in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:662
    #36 0x558f03e995db in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21
    #37 0x558f03e995db in std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84
    #38 0x558f03e995db in ?? ??:0
    #39 0x7f97f6f616b9 in start_thread ??:?
    #40 0x7f97f6f616b9 in ?? ??:0

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x558f03a0dc3f in __interceptor_malloc /checkout/src/compiler-rt/lib/lsan/lsan_interceptors.cc:56 (discriminator 2)
    #1 0x558f03a0dc3f in ?? ??:0
    #2 0x558f039d3adc in alloc::heap::allocate /checkout/src/liballoc/heap.rs:136
    #3 0x558f039d3adc in ?? ??:0
    #4 0x558f039d3a5d in alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:231
    #5 0x558f039d3a5d in ?? ??:0
    #6 0x558f039d6be6 in alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:243
    #7 0x558f039d6be6 in mio::poll::{{impl}}::new2 /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:1388
    #8 0x558f039d6be6 in ?? ??:0
    #9 0x558f0384d6b2 in tokio_core::reactor::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:158
    #10 0x558f0384d6b2 in ?? ??:0
    #11 0x558f02f1b862 in tikv::util::worker::future::poll<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:77
    #12 0x558f02f1b862 in ?? ??:0
    #13 0x558f03208c0e in tikv::util::worker::future::{{impl}}::start::{{closure}}<u64,tikv::util::worker::future::test::StepRunner> /home/pingcap/workspace/tikv/src/util/worker/future.rs:115
    #14 0x558f03208c0e in ?? ??:0
    #15 0x558f0292e912 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> /checkout/src/libstd/sys_common/backtrace.rs:136
    #16 0x558f0292e912 in ?? ??:0
    #17 0x558f02964dba in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:364
    #18 0x558f02964dba in ?? ??:0
    #19 0x558f02839e52 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296
    #20 0x558f02839e52 in ?? ??:0
    #21 0x558f02969272 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:454
    #22 0x558f02969272 in ?? ??:0
    #23 0x558f03ea1dcc in panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98
    #24 0x558f03ea1dcc in ?? ??:0
    #25 0x558f02967475 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:433
    #26 0x558f02967475 in ?? ??:0
    #27 0x558f02956e39 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361
    #28 0x558f02956e39 in ?? ??:0
    #29 0x558f02962581 in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:363
    #30 0x558f02962581 in ?? ??:0
    #31 0x558f02c524a7 in alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:652
    #32 0x558f02c524a7 in ?? ??:0
    #33 0x558f03e995db in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:662
    #34 0x558f03e995db in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21
    #35 0x558f03e995db in std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84
    #36 0x558f03e995db in ?? ??:0
    #37 0x7f97f6f616b9 in start_thread ??:?
    #38 0x7f97f6f616b9 in ?? ??:0

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x558f03a0dc3f in __interceptor_malloc /checkout/src/compiler-rt/lib/lsan/lsan_interceptors.cc:56 (discriminator 2)
    #1 0x558f03a0dc3f in ?? ??:0
    #2 0x558f039d3adc in alloc::heap::allocate /checkout/src/liballoc/heap.rs:136
    #3 0x558f039d3adc in ?? ??:0
    #4 0x558f039d3a5d in alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:231
    #5 0x558f039d3a5d in ?? ??:0
    #6 0x558f039d7f77 in alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:243
    #7 0x558f039d7f77 in mio::poll::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:1868
    #8 0x558f039d7f77 in ?? ??:0
    #9 0x558f039d54d2 in mio::poll::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:617
    #10 0x558f039d54d2 in ?? ??:0
    #11 0x558f0384cc8a in tokio_core::reactor::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:157
    #12 0x558f0384cc8a in ?? ??:0
    #13 0x558f02f1b862 in tikv::util::worker::future::poll<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:77
    #14 0x558f02f1b862 in ?? ??:0
    #15 0x558f03208c0e in tikv::util::worker::future::{{impl}}::start::{{closure}}<u64,tikv::util::worker::future::test::StepRunner> /home/pingcap/workspace/tikv/src/util/worker/future.rs:115
    #16 0x558f03208c0e in ?? ??:0
    #17 0x558f0292e912 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> /checkout/src/libstd/sys_common/backtrace.rs:136
    #18 0x558f0292e912 in ?? ??:0
    #19 0x558f02964dba in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:364
    #20 0x558f02964dba in ?? ??:0
    #21 0x558f02839e52 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296
    #22 0x558f02839e52 in ?? ??:0
    #23 0x558f02969272 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:454
    #24 0x558f02969272 in ?? ??:0
    #25 0x558f03ea1dcc in panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98
    #26 0x558f03ea1dcc in ?? ??:0
    #27 0x558f02967475 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:433
    #28 0x558f02967475 in ?? ??:0
    #29 0x558f02956e39 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361
    #30 0x558f02956e39 in ?? ??:0
    #31 0x558f02962581 in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:363
    #32 0x558f02962581 in ?? ??:0
    #33 0x558f02c524a7 in alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:652
    #34 0x558f02c524a7 in ?? ??:0
    #35 0x558f03e995db in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:662
    #36 0x558f03e995db in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21
    #37 0x558f03e995db in std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84
    #38 0x558f03e995db in ?? ??:0
    #39 0x7f97f6f616b9 in start_thread ??:?
    #40 0x7f97f6f616b9 in ?? ??:0

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x558f03a0dc3f in __interceptor_malloc /checkout/src/compiler-rt/lib/lsan/lsan_interceptors.cc:56 (discriminator 2)
    #1 0x558f03a0dc3f in ?? ??:0
    #2 0x558f039d3adc in alloc::heap::allocate /checkout/src/liballoc/heap.rs:136
    #3 0x558f039d3adc in ?? ??:0
    #4 0x558f039d3a5d in alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:231
    #5 0x558f039d3a5d in ?? ??:0
    #6 0x558f039d6be6 in alloc::boxed::{{impl}}::new<mio::poll::ReadinessNode> /checkout/src/liballoc/boxed.rs:243
    #7 0x558f039d6be6 in mio::poll::{{impl}}::new2 /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:1388
    #8 0x558f039d6be6 in ?? ??:0
    #9 0x558f0384cfbf in tokio_core::reactor::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:164
    #10 0x558f0384cfbf in ?? ??:0
    #11 0x558f02f1b862 in tikv::util::worker::future::poll<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:77
    #12 0x558f02f1b862 in ?? ??:0
    #13 0x558f03208c0e in tikv::util::worker::future::{{impl}}::start::{{closure}}<u64,tikv::util::worker::future::test::StepRunner> /home/pingcap/workspace/tikv/src/util/worker/future.rs:115
    #14 0x558f03208c0e in ?? ??:0
    #15 0x558f0292e912 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> /checkout/src/libstd/sys_common/backtrace.rs:136
    #16 0x558f0292e912 in ?? ??:0
    #17 0x558f02964dba in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:364
    #18 0x558f02964dba in ?? ??:0
    #19 0x558f02839e52 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296
    #20 0x558f02839e52 in ?? ??:0
    #21 0x558f02969272 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:454
    #22 0x558f02969272 in ?? ??:0
    #23 0x558f03ea1dcc in panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98
    #24 0x558f03ea1dcc in ?? ??:0
    #25 0x558f02967475 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:433
    #26 0x558f02967475 in ?? ??:0
    #27 0x558f02956e39 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361
    #28 0x558f02956e39 in ?? ??:0
    #29 0x558f02962581 in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:363
    #30 0x558f02962581 in ?? ??:0
    #31 0x558f02c524a7 in alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:652
    #32 0x558f02c524a7 in ?? ??:0
    #33 0x558f03e995db in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:662
    #34 0x558f03e995db in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21
    #35 0x558f03e995db in std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84
    #36 0x558f03e995db in ?? ??:0
    #37 0x7f97f6f616b9 in start_thread ??:?
    #38 0x7f97f6f616b9 in ?? ??:0

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x558f03a0dc3f in __interceptor_malloc /checkout/src/compiler-rt/lib/lsan/lsan_interceptors.cc:56 (discriminator 2)
    #1 0x558f03a0dc3f in ?? ??:0
    #2 0x558f039d3adc in alloc::heap::allocate /checkout/src/liballoc/heap.rs:136
    #3 0x558f039d3adc in ?? ??:0
    #4 0x558f039d3a5d in alloc::heap::exchange_malloc /checkout/src/liballoc/heap.rs:231
    #5 0x558f039d3a5d in ?? ??:0
    #6 0x558f039cd96f in alloc::arc::{{impl}}::new<mio::poll::ReadinessQueueInner> /checkout/src/liballoc/arc.rs:278
    #7 0x558f039cd96f in ?? ??:0
    #8 0x558f039d8333 in mio::poll::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:1874
    #9 0x558f039d8333 in ?? ??:0
    #10 0x558f039d54d2 in mio::poll::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.6/src/poll.rs:617
    #11 0x558f039d54d2 in ?? ??:0
    #12 0x558f0384cc8a in tokio_core::reactor::{{impl}}::new /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:157
    #13 0x558f0384cc8a in ?? ??:0
    #14 0x558f02f1b862 in tikv::util::worker::future::poll<tikv::util::worker::future::test::StepRunner,u64> /home/pingcap/workspace/tikv/src/util/worker/future.rs:77
    #15 0x558f02f1b862 in ?? ??:0
    #16 0x558f03208c0e in tikv::util::worker::future::{{impl}}::start::{{closure}}<u64,tikv::util::worker::future::test::StepRunner> /home/pingcap/workspace/tikv/src/util/worker/future.rs:115
    #17 0x558f03208c0e in ?? ??:0
    #18 0x558f0292e912 in std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> /checkout/src/libstd/sys_common/backtrace.rs:136
    #19 0x558f0292e912 in ?? ??:0
    #20 0x558f02964dba in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:364
    #21 0x558f02964dba in ?? ??:0
    #22 0x558f02839e52 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:296
    #23 0x558f02839e52 in ?? ??:0
    #24 0x558f02969272 in std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panicking.rs:454
    #25 0x558f02969272 in ?? ??:0
    #26 0x558f03ea1dcc in panic_unwind::__rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:98
    #27 0x558f03ea1dcc in ?? ??:0
    #28 0x558f02967475 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:433
    #29 0x558f02967475 in ?? ??:0
    #30 0x558f02956e39 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:361
    #31 0x558f02956e39 in ?? ??:0
    #32 0x558f02962581 in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:363
    #33 0x558f02962581 in ?? ??:0
    #34 0x558f02c524a7 in alloc::boxed::{{impl}}::call_box<(),closure> /checkout/src/liballoc/boxed.rs:652
    #35 0x558f02c524a7 in ?? ??:0
    #36 0x558f03e995db in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:662
    #37 0x558f03e995db in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:21
    #38 0x558f03e995db in std::sys::imp::thread::{{impl}}::new::thread_start /checkout/src/libstd/sys/unix/thread.rs:84
    #39 0x558f03e995db in ?? ??:0
    #40 0x7f97f6f616b9 in start_thread ??:?
    #41 0x7f97f6f616b9 in ?? ??:0

SUMMARY: LeakSanitizer: 504 byte(s) leaked in 8 allocation(s).
error: test failed, to rerun pass '--lib'

```

**Comment by siddontang** [comment]
is it accepted for the mio and tokio leak here? do we need to upgrade them?

@andelf

**Comment by BusyJay** [comment]
Fail case can be constantly reproduced on windows.
