### ISSUE TITLE
test: test_peer_resolve failed 

### ISSUE THREAD

**Issue by choleraehyq** [pingcap/tikv#1985]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
`rustc 1.20.0-nightly (05b579766 2017-07-01)`

2. What operating system and processor architecture are you using?
```
[cholerae@x240s tikv]$ uname -a
Linux x240s 4.11.7-300.fc26.x86_64 #1 SMP Mon Jun 26 14:54:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
`make test`

4. What did you expect to see?
All tests passed.

5. What did you see instead?
```
[cholerae@x240s tikv]$ make test
# When SIP is enabled, DYLD_LIBRARY_PATH will not work in subshell, so we have to set it
# again here. LOCAL_DIR is defined in .travis.yml.
export DYLD_LIBRARY_PATH=":/lib" && \
export LOG_LEVEL=DEBUG && \
export RUST_BACKTRACE=full && \
cargo test --features "default"  -- --nocapture && \
cargo test --features "default" --bench benches  -- --nocapture  && \
if [[ "`uname`" == "Linux" ]]; then \
	export MALLOC_CONF=prof:true,prof_active:false && \
	cargo test --features "default"  --bin tikv-server -- --nocapture --ignored; \
fi
   Compiling tikv v0.0.1 (file:///home/cholerae/rustcode/tikv)
    Finished dev [unoptimized + debuginfo] target(s) in 287.34 secs
     Running target/debug/deps/tikv-e25798a89a5a1236

running 310 tests
test raft::errors::tests::test_storage_error_equal ... ok
test raft::log_unstable::test::test_maybe_first_index ... ok
test raft::log_unstable::test::test_maybe_last_index ... ok
test raft::errors::tests::test_error_equal ... ok
test raft::log_unstable::test::test_restore ... ok
test raft::log_unstable::test::test_maybe_term ... ok
test raft::log_unstable::test::test_stable_to ... ok
test raft::raft_log::test::test_append ... ok
test raft::log_unstable::test::test_truncate_and_append ... ok
test raft::raft_log::test::test_commit_to ... ok
test raft::raft_log::test::test_find_conflict ... ok
test raft::raft_log::test::test_is_outofbounds ... ok
test raft::raft_log::test::test_compaction_side_effects ... ok
test raft::raft_log::test::test_is_up_to_date ... ok
test raft::raft_log::test::test_log_restore ... ok
test raft::raft_log::test::test_has_next_ents ... ok
test raft::raft_log::test::test_next_ents ... ok
test raft::raft_log::test::test_log_maybe_append ... ok
test raft::raft_log::test::test_stable_to ... ok
test raft::raft_log::test::test_slice ... ok
test raft::raft_log::test::test_stable_to_with_snap ... ok
test raft::raft_log::test::test_term_with_unstable_snapshot ... ok
test raft::raft_log::test::test_term ... ok
test raft::raw_node::test::test_is_local_msg ... ok
test raft::storage::test::test_storage_apply_snapshot ... ok
test raft::storage::test::test_storage_append ... ok
test raft::storage::test::test_storage_compact ... ok
test raft::raft_log::test::test_unstable_ents ... ok
test raft::storage::test::test_storage_entries ... ok
test raft::storage::test::test_storage_first_index ... ok
test raft::storage::test::test_storage_term ... ok
test raft::storage::test::test_storage_last_index ... ok
test raft::storage::test::test_storage_create_snapshot ... ok
test raftstore::coprocessor::dispatcher::test::test_coprocessor_host ... ok
test raft::raft_log::test::test_compaction ... ok
test raftstore::coprocessor::split_observer::test::test_forget_encode ... ok
test raftstore::coprocessor::split_observer::test::test_split ... ok
test raftstore::store::bootstrap::tests::test_bootstrap ... ok
test raftstore::store::config::tests::test_config_validate ... ok
test raftstore::coprocessor::region_snapshot::tests::test_peekable ... ok
test raftstore::coprocessor::region_snapshot::tests::test_reverse_iterate ... ok
test raftstore::coprocessor::region_snapshot::tests::test_iterate ... ok
test raftstore::store::engine::tests::test_base ... ok
test raftstore::store::keys::tests::test_data_key ... ok
test raftstore::store::keys::tests::test_raft_log_key ... ok
test raftstore::store::keys::tests::test_raft_log_sort ... ok
test raftstore::store::keys::tests::test_region_id_key ... ok
test raftstore::store::keys::tests::test_region_meta_key ... ok
test raftstore::store::engine::tests::test_peekable ... ok
test raftstore::store::engine::tests::test_scan ... ok
test raftstore::store::peer_storage::test::test_canceling_snapshot ... ok
test raftstore::store::engine::tests::test_delete_all_in_range ... ok
test raftstore::store::msg::tests::test_sender ... ok
test raftstore::store::peer_storage::test::test_storage_apply_snapshot_with_old_format ... ok
test raftstore::store::peer_storage::test::test_storage_apply_snapshot_with_sst_file_format ... ok
test raftstore::store::peer_storage::test::test_storage_create_snapshot_with_sst_format ... ok
test raftstore::store::peer_storage::test::test_storage_create_snapshot_with_plain_format ... ok
test raftstore::store::peer_storage::test::test_storage_append ... ok
test raftstore::store::peer_storage::test::test_storage_compact ... ok
test raftstore::store::peer_storage::test::test_try_finish_snapshot ... ok
test raftstore::store::snap::test::test_snap_mgr_create_dir ... ok
test raftstore::store::snap::test::test_snap_mgr_v1 ... ok
test raftstore::store::snap::test::test_snap_deletion_on_registry ... ok
test raftstore::store::snap::test::test_snap_mgr_v2 ... ok
test raftstore::store::snap::v1::test::test_snap_file ... ok
test raftstore::store::snap::v1::test::test_snap_validate ... ok
test raftstore::store::snap::v2::test::test_display_path ... ok
test raftstore::store::peer_storage::test::test_storage_term ... ok
test raftstore::store::snap::v2::test::test_empty_snap_validation ... ok
test raftstore::store::snap::v2::test::test_gen_snapshot_meta ... ok
test raftstore::store::snap::v2::test::test_empty_snap_file ... ok
test raftstore::store::snap::test::test_snap_v1_v2_compatible ... ok
test raftstore::store::snap::v2::test::test_non_empty_snap_validation ... ok
test raftstore::store::snap::v2::test::test_non_empty_snap_file ... ok
test raftstore::store::util::tests::test_check_key_in_region ... ok
test raftstore::store::util::tests::test_conf_change_type_str ... ok
test raftstore::store::util::tests::test_epoch_stale ... ok
test raftstore::store::util::tests::test_first_vote_msg ... ok
test raftstore::store::util::tests::test_peer ... ok
test raftstore::store::snap::v2::test::test_snap_corruption_on_meta_file ... ok
test raftstore::store::worker::apply::tests::test_basic_flow ... ok
test raftstore::store::worker::apply::tests::test_should_flush_to_engine ... ok
test raftstore::store::snap::v2::test::test_snap_corruption_on_size_or_checksum ... ok
test raftstore::store::worker::apply::tests::test_handle_raft_committed_entries ... ok
test raftstore::store::worker::consistency_check::test::test_consistency_check ... ok
test raftstore::store::peer_storage::test::test_storage_entries ... ok
test server::config::tests::test_config_validate ... ok
test server::config::tests::test_end_point_txn_concurrency ... ok
test server::config::tests::test_validate_endpoint_cfg ... ok
test server::coprocessor::endpoint::tests::test_get_req_type_str ... ok
test raftstore::store::worker::raftlog_gc::test::test_gc_raft_log ... ok
test raftstore::store::worker::split_check::tests::test_split_check ... ok
test server::coprocessor::endpoint::tests::test_topn_heap ... ok
test server::coprocessor::endpoint::tests::test_topn_heap_with_cmp_error ... ok
test server::coprocessor::endpoint::tests::test_topn_heap_with_few_data ... ok
test server::coprocessor::endpoint::tests::test_topn_limit_oom ... ok
test server::coprocessor::endpoint::tests::test_req_outdated ... ok
test server::coprocessor::executor::index_scan::test::test_multiple_ranges ... ok
test server::coprocessor::executor::index_scan::test::test_include_pk ... ok
test server::coprocessor::endpoint::tests::test_too_many_reqs ... ok
test server::coprocessor::executor::index_scan::test::test_reverse_scan ... ok
test server::coprocessor::executor::limit::test::test_limit_executor ... ok
test server::coprocessor::executor::scanner::test::test_init_with_range ... ok
test server::coprocessor::executor::scanner::test::test_point_get ... ok
test server::coprocessor::executor::scanner::test::test_reverse_scan ... ok
test server::coprocessor::executor::scanner::test::test_scan ... ok
test server::coprocessor::executor::scanner::test::test_scan_key_only ... ok
test server::coprocessor::executor::selection::tests::test_selection_executor_condition ... ok
test server::coprocessor::executor::selection::tests::test_selection_executor_simple ... ok
test server::coprocessor::executor::table_scan::test::test_multiple_ranges ... ok
test server::coprocessor::executor::table_scan::test::test_point_get ... ok
test server::coprocessor::executor::topn::test::test_topn_heap ... ok
test server::coprocessor::executor::topn::test::test_topn_heap_with_cmp_error ... ok
test server::node::tests::test_check_region_epoch ... ok
test server::resolve::tests::test_resolve_store_state_offline ... ok
test server::resolve::tests::test_resolve_store_state_tombstone ... ok
test server::resolve::tests::test_resolve_store_state_up ... ok
test server::resolve::tests::test_store_address_refresh ... ok
test server::coprocessor::executor::table_scan::test::test_reverse_scan ... ok
test server::coprocessor::executor::topn::test::test_topn_executor ... ok
test storage::engine::tests::rocksdb ... ok
test storage::engine::tests::rocksdb_reopen ... ok
test storage::mvcc::lock::tests::test_lock ... ok
test storage::mvcc::lock::tests::test_lock_type ... ok
test storage::mvcc::txn::tests::test_gc ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_commit_err ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_commit_ok ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_prewrite ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_read ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_rollback ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_rollback_after_commit ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_rollback_before_prewrite ... ok
test storage::mvcc::txn::tests::test_mvcc_txn_rollback_err ... ok
test storage::mvcc::txn::tests::test_read_commit ... ok
test storage::mvcc::txn::tests::test_rollback_del ... ok
test storage::mvcc::txn::tests::test_rollback_lock ... ok
test storage::mvcc::txn::tests::test_scan_keys ... ok
test storage::mvcc::txn::tests::test_skip_constraint_check ... ok
test storage::mvcc::txn::tests::test_write ... ok
test storage::mvcc::txn::tests::test_write_size ... ok
test storage::mvcc::write::tests::test_write ... ok
test storage::mvcc::write::tests::test_write_type ... ok
test storage::tests::test_batch_get ... ok
test storage::tests::test_cleanup ... ok
test storage::tests::test_get_put ... ok
test storage::tests::test_high_priority_get_put ... ok
test storage::tests::test_high_priority_no_block ... ok
test storage::tests::test_put_with_err ... ok
test storage::tests::test_scan ... ok
test storage::tests::test_sched_too_busy ... ok
test storage::tests::test_txn ... ok
test storage::txn::latch::tests::test_wakeup ... ok
test storage::txn::latch::tests::test_wakeup_by_multi_cmds ... ok
test storage::txn::scheduler::tests::test_command_latches ... ok
test storage::txn::store::test::test_snapshot_store_batch_get ... ok
test storage::txn::store::test::test_snapshot_store_get ... ok
test storage::txn::store::test::test_snapshot_store_reverse_scan ... ok
test storage::txn::store::test::test_snapshot_store_reverse_seek ... ok
test storage::txn::store::test::test_snapshot_store_scan ... ok
test storage::txn::store::test::test_snapshot_store_seek ... ok
test util::buf::tests::test_buf_read ... ok
test raftstore::store::worker::compact::test::test_compact_range ... ok
test util::buf::tests::test_read_from ... ok
test util::buf::tests::test_ensure ... ok
test util::buf::tests::test_write_all ... ok
test util::buf::tests::test_shrink_to ... ok
test util::clocktime::tests::test_now_monotonic_raw ... ok
test util::buf::tests::test_write_to ... ok
test util::codec::bytes::tests::bench_encode ... ok
test util::codec::bytes::tests::test_compact_codec ... ok
test util::codec::bytes::tests::test_dec_bytes_fail ... ok
test util::codec::bytes::tests::test_enc_dec_bytes ... ok
test util::codec::bytes::tests::test_encode_bytes_compare ... ok
test util::codec::bytes::tests::test_max_encoded_bytes_size ... ok
test util::codec::convert::test::test_bytes_to_f64 ... ok
test util::codec::convert::test::test_bytes_to_i64 ... ok
test util::codec::convert::test::test_get_valid_float_prefix ... ok
test util::codec::convert::test::test_handle_truncate ... ok
test util::codec::convert::test::test_invalid_get_valid_int_prefix ... ok
test util::codec::convert::test::test_valid_get_valid_int_prefix ... ok
test util::codec::datum::test::test_coerce_datum ... ok
test util::codec::datum::test::test_datum_cmp ... ok
test util::codec::datum::test::test_datum_codec ... ok
test util::codec::datum::test::test_datum_to_bool ... ok
test util::codec::datum::test::test_split_datum ... ok
test util::codec::mysql::decimal::test::test_add ... ok
test util::codec::mysql::decimal::test::test_cmp ... ok
test util::codec::mysql::decimal::test::test_codec ... ok
test util::codec::mysql::decimal::test::test_div_mod ... ok
test util::codec::mysql::decimal::test::test_f64 ... ok
test util::codec::mysql::decimal::test::test_from_i64 ... ok
test util::codec::mysql::decimal::test::test_from_u64 ... ok
test util::codec::mysql::decimal::test::test_max_decimal ... ok
test util::codec::mysql::decimal::test::test_mul ... ok
test util::codec::mysql::decimal::test::test_round ... ok
test util::codec::mysql::decimal::test::test_shift ... ok
test util::codec::mysql::decimal::test::test_string ... ok
test util::codec::mysql::decimal::test::test_sub ... ok
test util::codec::mysql::decimal::test::test_to_i64 ... ok
test util::codec::mysql::decimal::test::test_to_u64 ... ok
test util::codec::mysql::duration::test::test_parse ... ok
test util::codec::mysql::duration::test::test_to_decimal ... ok
test util::codec::mysql::json::binary::test::test_json_binary ... ok
test util::codec::mysql::json::binary::test::test_type_code ... ok
test util::codec::mysql::json::comparison::test::test_cmp_json_between_diff_type ... ok
test util::codec::mysql::json::comparison::test::test_cmp_json_between_same_type ... ok
test util::codec::mysql::json::functions::test::test_decode_escaped_unicode ... ok
test util::codec::mysql::json::functions::test::test_json_extract ... ok
test util::codec::mysql::json::functions::test::test_json_unquote ... ok
test util::codec::mysql::json::json_merge::test::test_merge ... ok
test util::codec::mysql::json::json_modify::test::test_json_modify ... ok
test util::codec::mysql::json::json_type::test::test_type ... ok
test util::codec::mysql::json::path_expr::test::test_parse_json_path_expr ... ok
test util::codec::mysql::json::path_expr::test::test_parse_json_path_expr_contains_any_asterisk ... ok
test util::codec::mysql::json::path_expr::test::test_path_expression_flag ... ok
test util::codec::mysql::json::serde::test::test_from_str ... ok
test util::codec::mysql::json::serde::test::test_from_str_for_object ... ok
test util::codec::mysql::test::test_parse_frace ... ok
thread 'server::server::tests::test_peer_resolve' panicked at 'assertion failed: rx.recv_timeout(Duration::from_secs(5)).is_ok()', src/server/server.rs:248
stack backtrace:
test storage::engine::tests::test_linear ... ok
test util::codec::bytes::tests::bench_decode ... ok
   0:     0x56269fe60be3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::he3d64830f983ab2f
test util::codec::mysql::time::test::test_compare ... ok
test util::codec::mysql::time::test::test_parse_datetime_format ... ok
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x56269fe5cf44 - std::sys_common::backtrace::_print::h52aedf7cbc42c8b1
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x56269fe64724 - std::panicking::default_hook::{{closure}}::h88d4869327f386e6
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x56269fe64213 - std::panicking::default_hook::h6063df813757b580
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x56269ef4810c - tikv::util::panic_hook::track_hook::{{closure}}::h4bf476f2fb5fb550
test util::codec::mysql::time::test::test_codec ... ok
test util::codec::number::test::encode_f64::serialize ... ok
test util::codec::number::test::encode_f64::test_order ... ok
test util::codec::number::test::encode_f64_desc::serialize ... ok
test util::codec::number::test::encode_f64_desc::test_order ... ok
test util::codec::number::test::encode_i64::serialize ... ok
test util::codec::number::test::encode_i64::test_order ... ok
test util::codec::number::test::encode_i64_desc::serialize ... ok
test util::codec::number::test::encode_i64_desc::test_order ... ok
test util::codec::number::test::encode_u64::serialize ... ok
test util::codec::number::test::encode_u64::test_order ... ok
test util::codec::number::test::encode_u64_desc::serialize ... ok
test util::codec::number::test::encode_u64_desc::test_order ... ok
test util::codec::number::test::f64_desc_eof ... ok
test util::codec::number::test::f64_eof ... ok
test util::codec::number::test::i64_desc_eof ... ok
test util::codec::number::test::i64_eof ... ok
test util::codec::number::test::test_var_eof ... ok
test util::codec::number::test::test_var_f64_le ... ok
test util::codec::number::test::test_var_u64_codec ... ok
test util::codec::number::test::u64_desc_eof ... ok
test util::codec::number::test::u64_eof ... ok
test util::codec::number::test::var_i64_codec ... ok
test util::codec::number::test::var_i64_little_endian_codec ... ok
test util::codec::number::test::var_u16_codec ... ok
test util::codec::number::test::var_u32_codec ... ok
test util::codec::table::test::test_idx_codec ... ok
test util::codec::table::test::test_index_key_codec ... ok
test util::codec::table::test::test_row_codec ... ok
test util::codec::table::test::test_row_key_codec ... ok
test util::config::test::test_check_addrs ... ok
test util::config::test::test_check_kernel ... ok
test util::config::test::test_parse_readable_int ... ok
test util::config::test::test_parse_rocksdb_wal_recovery_mode ... ok
test util::config::test::test_store_labels ... ok
test util::file::test::test_delete_file_if_exist ... ok
test util::file::test::test_file_exists ... ok
test util::file::test::test_get_file_size ... ok
test util::file_log::tests::test_one_day_before ... ok
test util::file_log::tests::test_rotating_file_logger ... ok
test util::rocksdb::tests::test_check_and_open ... ok
test util::sockopt::unix::tests::test_mio_sock_opt ... ok
test util::sockopt::unix::tests::test_std_sock_opt ... ok
test util::tests::test_cfs_diff ... ok
test util::tests::test_defer ... ok
test util::tests::test_duration_to ... ok
test util::tests::test_fixed_ring_queue ... ok
test util::tests::test_limit_size ... ok
test util::tests::test_rwlock_deadlock ... ok
test util::tests::test_to_socket_addr ... ok
test util::thread_metrics::tests::test_get_thread_name ... ok
test util::thread_metrics::tests::test_get_thread_stat ... ok
test util::thread_metrics::tests::test_thread_stat ... ok
test util::threadpool::test::test_for_tasks_with_different_cost ... ok
test util::threadpool::test::test_get_task_count ... ok
test util::threadpool::test::test_small_group_first_queue ... ok
test util::threadpool::test::test_throttled_queue ... ok
                               at src/util/panic_hook.rs:61
   5:     0x56269ea197ff - <std::thread::local::LocalKey<T>>::with::h01b35e1cedc11333
                               at /checkout/src/libstd/thread/local.rs:265
   6:     0x56269ef4802e - tikv::util::panic_hook::track_hook::h9709e5599ae35873
                               at src/util/panic_hook.rs:55
   7:     0x56269ebb7ba8 - core::ops::function::Fn::call::h9984cd7bef4788d3
                               at /checkout/src/libcore/ops/function.rs:48
   8:     0x56269fe64be9 - std::panicking::rust_panic_with_hook::h6905d84ff67729c6
                               at /checkout/src/libstd/panicking.rs:550
   9:     0x56269e9b41a9 - std::panicking::begin_panic::h634da99c9b6e1d42
                               at /checkout/src/libstd/panicking.rs:511
  10:     0x56269f1ddce4 - tikv::server::server::tests::test_peer_resolve::h3b9166ddcc13f21f
                               at src/server/server.rs:248
  11:     0x56269fa2f0c1 - <F as test::FnBox<T>>::call_box::hb4d36130c4fa95cb
                               at /checkout/src/libtest/lib.rs:1479
                               at /checkout/src/libcore/ops/function.rs:143
                               at /checkout/src/libtest/lib.rs:140
  12:     0x56269fe6bdbc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  13:     0x56269fa1e71c - std::sys_common::backtrace::__rust_begin_short_backtrace::h02000c47e40c5cbb
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libtest/lib.rs:1418
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  14:     0x56269fa1f462 - std::panicking::try::do_call::h3c3849a39868a22b
                               at /checkout/src/libstd/thread/mod.rs:364
                               at /checkout/src/libstd/panic.rs:296
                               at /checkout/src/libstd/panicking.rs:454
  15:     0x56269fe6bdbc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  16:     0x56269fa27c52 - <F as alloc::boxed::FnBox<A>>::call_box::h9e5cd2d28244813c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/thread/mod.rs:363
                               at /checkout/src/liballoc/boxed.rs:652
  17:     0x56269fe635cb - std::sys::imp::thread::Thread::new::thread_start::h5acc06803c603286
                               at /checkout/src/liballoc/boxed.rs:662
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  18:     0x7f57d43d736c - start_thread
  19:     0x7f57d4e21b9e - clone
  20:                0x0 - <unknown>
test server::server::tests::test_peer_resolve ... FAILED
test util::transport::tests::test_sendch ... ok
test util::codec::mysql::time::test::test_parse_datetime ... ok
test util::transport::tests::test_sync_sendch ... ok
test util::time_monitor::tests::test_time_monitor ... ok
test util::worker::future::test::test_future_worker ... ok
test util::transport::tests::test_sendch_full ... ok
test util::worker::test::test_batch ... ok
test util::worker::test::test_threaded ... ok
test util::transport::tests::test_sync_sendch_full ... ok
test util::xeval::evaluator::test::test_context ... ok
test util::xeval::evaluator::test::test_eval_case_when ... ok
test util::xeval::evaluator::test::test_eval_cmp ... ok
test util::xeval::evaluator::test::test_eval_coalesce ... ok
test util::xeval::evaluator::test::test_eval_datum_col ... ok
test util::xeval::evaluator::test::test_eval_div ... ok
test util::xeval::evaluator::test::test_eval_if ... ok
test util::xeval::evaluator::test::test_eval_if_null ... ok
test util::xeval::evaluator::test::test_eval_int_div ... ok
test util::xeval::evaluator::test::test_eval_is_null ... ok
test util::xeval::evaluator::test::test_eval_like ... ok
test util::xeval::evaluator::test::test_eval_logic ... ok
test util::xeval::evaluator::test::test_eval_minus ... ok
test util::xeval::evaluator::test::test_eval_mul ... ok
test util::xeval::evaluator::test::test_eval_null_if ... ok
test util::xeval::evaluator::test::test_eval_plus ... ok
test util::xeval::evaluator::test::test_eval_rem ... ok
test util::xeval::evaluator::test::test_where_in ... ok
test util::worker::test::test_worker ... ok
test util::worker::test::test_autowired_batch ... ok
test util::codec::mysql::time::test::test_to_dec ... ok

failures:

failures:
    server::server::tests::test_peer_resolve

test result: FAILED. 309 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
make: *** [Makefile:60: test] Error 101
```

**Comment by siddontang** [comment]
PTAL @disksing

**Comment by disksing** [comment]
@choleraehyq 
Do you have any http proxy set on your os? You may try to disable proxy or to ensure that localhost does not go through the proxy, then try `make dev` again.

**Comment by choleraehyq** [comment]
@disksing 
`make test` passed after I disabled my proxy. Sorry to bother you.
