### ISSUE TITLE
tikv core dumped after upgrade and revert

### ISSUE THREAD

**Issue by Darren** [pingcap/tikv#2013]
I try to update TiDB from  2017-06-06 nightly verison   to 2017-07-07 nightly verison.
but because  pd-server failed to start due to https://github.com/pingcap/tidb/issues/3668
So I revert all binary to 2017-06-06 nightly verison, now one of tikv-server core dumped,
I can provide download link of the orginal core file if asked.

Version:
```
# ./tikv-server  --version
TiKV 0.0.1
Git Commit Hash: 3050fef8565787a655e30de503b49149435fdeab
UTC Build Time:  2017-06-06 02:04:12
Rust Version:    1.17.0-nightly (ccce2c6eb 2017-03-27)
```

tikv config
```
# grep '^[^# ]' tk-config.toml 
[server]
log-level = "error"
capacity = 536870912000 # 500G 
[metric]
interval = "10s"
address = "192.168.20.73:9091"
job = "tikv"
[raftstore]
sync-log = false
[pd]
[rocksdb]
[rocksdb.defaultcf]
compression-per-level = "snappy:snappy:lz4:lz4:lz4:zstd:zstd"
[rocksdb.writecf]
[rocksdb.raftcf]
[rocksdb.lockcf]
[storage]

```

stacktrace:
```
gdb tikv-server core.70575 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /tmp/tikv-server...done.

warning: exec file is newer than core file.
[New LWP 70600]
[New LWP 70604]
[New LWP 70605]
[New LWP 70607]
[New LWP 70608]
[New LWP 70610]
[New LWP 70611]
[New LWP 70615]
[New LWP 70617]
[New LWP 70606]
[New LWP 70616]
[New LWP 70620]
[New LWP 70614]
[New LWP 70619]
[New LWP 70621]
[New LWP 70609]
[New LWP 70628]
[New LWP 70635]
[New LWP 70647]
[New LWP 70651]
[New LWP 70639]
[New LWP 70652]
[New LWP 70576]
[New LWP 70593]
[New LWP 70618]
[New LWP 70592]
[New LWP 70591]
[New LWP 70612]
[New LWP 70596]
[New LWP 70622]
[New LWP 70625]
[New LWP 70629]
[New LWP 70636]
[New LWP 70653]
[New LWP 70641]
[New LWP 70613]
[New LWP 70581]
[New LWP 70631]
[New LWP 70595]
[New LWP 70632]
[New LWP 70594]
[New LWP 70575]
[New LWP 70623]
[New LWP 70633]
[New LWP 70626]
[New LWP 70645]
[New LWP 70637]
[New LWP 70642]
[New LWP 70630]
[New LWP 70582]
[New LWP 70597]
[New LWP 70646]
[New LWP 70624]
[New LWP 70638]
[New LWP 70634]
[New LWP 70643]
[New LWP 70627]
[New LWP 70598]
[New LWP 70640]
[New LWP 70599]
[New LWP 70650]
[New LWP 70649]
[New LWP 70648]
[New LWP 70644]

warning: .dynamic section for "/lib64/libdl.so.2" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/librt.so.1" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libpthread.so.0" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libgcc_s.so.1" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libc.so.6" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/ld-linux-x86-64.so.2" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libm.so.6" is not at the expected address (wrong library or version mismatch?)

warning: Could not load shared library symbols for efined in file .
Do you need "set solib-search-path" or "set sysroot"?
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `./tikv-server --log-level info --pd=192.168.20.71:2379,192.168.72.51:2379,192.1'.
Program terminated with signal 11, Segmentation fault.
#0  rocksdb::FullFilterBlockReader::MayMatch (this=<optimized out>, entry=...) at table/full_filter_block.cc:99
99	table/full_filter_block.cc: No such file or directory.
warning: Missing auto-load scripts referenced in section .debug_gdb_scripts
of file /tmp/tikv-server
Use `info auto-load python [REGEXP]' to list them.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64 libgcc-4.8.5-11.el7.x86_64
(gdb) bt full
#0  rocksdb::FullFilterBlockReader::MayMatch (this=<optimized out>, entry=...) at table/full_filter_block.cc:99
No locals.
#1  0x00007f72c1a9d90b in rocksdb::BlockBasedTable::FullFilterKeyMayMatch (this=0x7f72ada0c1c0, read_options=..., filter=0x7f72ada26070, internal_key=..., no_io=<optimized out>) at table/block_based_table_reader.cc:1594
        user_key = {data_ = 0x7f72adff4529 "\001\003", size_ = 11}
        const_ikey_ptr = 0x7f72adff41f0
        filter = 0x7f72ada26070
        this = 0x7f72ada0c1c0
        no_io = false
        internal_key = @0x7f72adff41f0: {data_ = 0x7f72adff4529 "\001\003", size_ = 19}
        read_options = @0x7f72ada39810: {verify_checksums = true, fill_cache = true, snapshot = 0x0, iterate_upper_bound = 0x0, read_tier = rocksdb::kReadAllTier, tailing = false, managed = false, total_order_seek = false, prefix_same_as_start = false, pin_data = false, background_purge_on_iterator_cleanup = false, readahead_size = 0, 
          ignore_range_deletions = false, max_skippable_internal_keys = 0}
#2  0x00007f72c1aa6091 in rocksdb::BlockBasedTable::Get (this=0x7f72ada0c1c0, read_options=..., key=..., get_context=0x7f72adff4340, skip_filters=<optimized out>) at table/block_based_table_reader.cc:1620
        s = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x7f72c1df639a "", 0x7f72c1df9d50 "Timeout Acquiring Mutex", 0x7f72c1df9d68 "Timeout waiting to lock key", 0x7f72c1df9dd0 "Failed to acquire lock due to max_num_locks limit", 0x7f72c1df9d84 "No space left on device", 0x7f72c1df9d9c "Deadlock", 
            0x7f72c1df9da5 "Stale file handle", 0x7f72c1df9db7 "Memory limit reached"}}
        filter_entry = <optimized out>
        filter = 0x7f72ada26070
#3  0x00007f72c1a29779 in rocksdb::TableCache::Get (this=0x7f72bfdcee00, options=..., internal_comparator=..., fd=..., k=..., get_context=0x7f72adff4340, file_read_hist=0x7f72bf685000, skip_filters=false, level=0) at db/table_cache.cc:336
        row_cache_entry = 0x0
        done = false
        row_cache_key = {buf_ = 0x7f72adff40e0 "\001", buf_size_ = 32, key_ = 0x7f72adff40e0 "\001", key_size_ = 0, space_ = "\001", '\000' <repeats 24 times>, "$\266\023\000\000\000", is_user_key_ = true}
        row_cache_entry_buffer = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f72c2356598 <std::string::_Rep::_S_empty_rep_storage+24> ""}}
        s = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x7f72c1df639a "", 0x7f72c1df9d50 "Timeout Acquiring Mutex", 0x7f72c1df9d68 "Timeout waiting to lock key", 0x7f72c1df9dd0 "Failed to acquire lock due to max_num_locks limit", 0x7f72c1df9d84 "No space left on device", 0x7f72c1df9d9c "Deadlock", 
            0x7f72c1df9da5 "Stale file handle", 0x7f72c1df9db7 "Memory limit reached"}}
        t = <optimized out>
        handle = 0x7f72ada38320
#4  0x00007f72c1a3df16 in rocksdb::Version::Get (this=0x7f72afe4e400, read_options=..., k=..., value=value@entry=0x7f72adff4680, status=status@entry=0x7f72adff4770, merge_context=merge_context@entry=0x7f72adff4460, range_del_agg=0x7f72adff44a0, value_found=0x0, key_exists=0x0, seq=0x0) at db/version_set.cc:969
        ikey = {data_ = 0x7f72adff4529 "\001\003", size_ = 19}
        user_key = {data_ = 0x7f72adff4529 "\001\003", size_ = 11}
        pinned_iters_mgr = {<rocksdb::Cleanable> = {cleanup_ = {function = 0x0, arg1 = 0x95be3ff501c90300, arg2 = 0x7f72ac2a7280, next = 0x0}}, pinning_enabled = false, pinned_ptrs_ = {<std::_Vector_base<std::pair<void*, void (*)(void*)>, std::allocator<std::pair<void*, void (*)(void*)> > >> = {
              _M_impl = {<std::allocator<std::pair<void*, void (*)(void*)> >> = {<__gnu_cxx::new_allocator<std::pair<void*, void (*)(void*)> >> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}}
        get_context = {ucmp_ = 0x7f72c23549c0 <rocksdb::BytewiseComparator()::bytewise>, merge_operator_ = 0x0, logger_ = 0x7f72be6c4bb0, statistics_ = 0x7f72be6819d0, state_ = rocksdb::GetContext::kNotFound, user_key_ = {data_ = 0x7f72adff4529 "\001\003", size_ = 11}, pinnable_val_ = 0x7f72adff4680, value_found_ = 0x0, merge_context_ = 0x7f72adff4460, 
          range_del_agg_ = 0x7f72adff44a0, env_ = 0x7f72c23528e0 <rocksdb::Env::Default()::default_env>, seq_ = 0x0, replay_log_ = 0x0, pinned_iters_mgr_ = 0x0}
        fp = {num_levels_ = 4, curr_level_ = 0, returned_file_level_ = 0, hit_file_level_ = 0, search_left_bound_ = 0, search_right_bound_ = 2147483647, level_files_brief_ = 0x7f72afe4e460, search_ended_ = false, is_hit_file_last_in_level_ = true, curr_file_level_ = 0x7f72afe4e468, curr_index_in_curr_level_ = 1, start_index_in_curr_level_ = 0, 
          user_key_ = {data_ = 0x7f72adff4529 "\001\003", size_ = 11}, ikey_ = {data_ = 0x7f72adff4529 "\001\003", size_ = 19}, file_indexer_ = 0x7f72afe4e500, user_comparator_ = 0x7f72c23549c0 <rocksdb::BytewiseComparator()::bytewise>, internal_comparator_ = 0x7f72bfd0e328}
        f = 0x7f72afe4e6d0
#5  0x00007f72c19a25c1 in rocksdb::DBImpl::GetImpl (this=0x7f72be6de000, read_options=..., column_family=<optimized out>, key=..., pinnable_val=0x7f72adff4680, value_found=0x0) at db/db_impl.cc:971
        perf_step_timer_get_from_output_files_time = {enabled_ = false, env_ = 0x0, start_ = 0, metric_ = 0x7f72adfff460}
        sw = {env_ = 0x7f72c23528e0 <rocksdb::Env::Default()::default_env>, statistics_ = 0x7f72be6819d0, hist_type_ = 0, elapsed_ = 0x0, overwrite_ = true, stats_enabled_ = true, start_time_ = 1499495544000072}
        perf_step_timer_get_snapshot_time = {enabled_ = false, env_ = 0x0, start_ = 0, metric_ = 0x7f72adfff440}
        cfh = <optimized out>
        cfd = 0x7f72bfd0e300
        sv = 0x7f72bfc82480
        snapshot = <optimized out>
        merge_context = {operand_list_ = {
            _M_t = {<std::_Tuple_impl<0ul, std::vector<rocksdb::Slice, std::allocator<rocksdb::Slice> >*, std::default_delete<std::vector<rocksdb::Slice, std::allocator<rocksdb::Slice> > > >> = {<std::_Tuple_impl<1ul, std::default_delete<std::vector<rocksdb::Slice, std::allocator<rocksdb::Slice> > > >> = {<std::_Head_base<1ul, std::default_delete<std::vector<rocksdb::Slice, std::allocator<rocksdb::Slice> > >, true>> = {<std::default_delete<std::vector<rocksdb::Slice, std::allocator<rocksdb::Slice> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Head_base<0ul, std::vector<rocksdb::Slice, std::allocator<rocksdb::Slice> >*, false>> = {
                  _M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, copied_operands_ = {
            _M_t = {<std::_Tuple_impl<0ul, std::vector<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >*, std::default_delete<std::vector<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >> = {<std::_Tuple_impl<1ul, std::default_delete<std::vector<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >> = {<std::_Head_base<1ul, std::default_delete<std::vector<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >, true>> = {<std::default_delete<std::vector<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Head_base<0ul, std::vector<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::unique_ptr<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::default_delete<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >*, false>> = {_M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, operands_reversed_ = true}
        range_del_agg = {upper_bound_ = 15397189681, rep_ = {
            _M_t = {<std::_Tuple_impl<0ul, rocksdb::RangeDelAggregator::Rep*, std::default_delete<rocksdb::RangeDelAggregator::Rep> >> = {<std::_Tuple_impl<1ul, std::default_delete<rocksdb::RangeDelAggregator::Rep> >> = {<std::_Head_base<1ul, std::default_delete<rocksdb::RangeDelAggregator::Rep>, true>> = {<std::default_delete<rocksdb::RangeDelAggregator::Rep>> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Head_base<0ul, rocksdb::RangeDelAggregator::Rep*, false>> = {_M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, icmp_ = @0x7f72bfd0e328, collapse_deletions_ = false}
        s = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x7f72c1df639a "", 0x7f72c1df9d50 "Timeout Acquiring Mutex", 0x7f72c1df9d68 "Timeout waiting to lock key", 0x7f72c1df9dd0 "Failed to acquire lock due to max_num_locks limit", 0x7f72c1df9d84 "No space left on device", 0x7f72c1df9d9c "Deadlock", 
            0x7f72c1df9da5 "Stale file handle", 0x7f72c1df9db7 "Memory limit reached"}}
        lkey = {start_ = 0x7f72adff4528 "\023\001\003", kstart_ = 0x7f72adff4529 "\001\003", end_ = 0x7f72adff453c "r\177", 
          space_ = "\023\001\003\000\000\000\000\032uR\347\001\a1x\276\225\003\000\000r\177\000\000\001\b\000\000\000\000\000\000\001\000\000\000\000\000\000\000P\237N\000\000\000\000\000\001\000\000\000\000\000\000\000\356\255`-\000\000\000\000\001\000\000\000\000\000\000\000Z", '\000' <repeats 15 times>, "\003", '\000' <repeats 15 times>, "\220y\326\277r\177\000\000\001", '\000' <repeats 31 times>, "\001", '\000' <repeats 24 times>, "$\266\023", '\000' <repeats 20 times>, " \352)\033\000\000\000"}
        skip_memtable = <optimized out>
        done = false
#6  0x00007f72c19a2b53 in rocksdb::DBImpl::Get (this=<optimized out>, read_options=..., column_family=<optimized out>, key=..., value=<optimized out>) at db/db_impl.cc:898
No locals.
#7  0x00007f72c19915d6 in rocksdb::DB::Get (this=this@entry=0x7f72be6de000, options=..., column_family=0x7f72bfdced20, key=..., value=value@entry=0x7f72adff4760) at ./include/rocksdb/db.h:316
        pinnable_val = {<rocksdb::Slice> = {data_ = 0x7f72c1df639a "", size_ = 0}, <rocksdb::Cleanable> = {cleanup_ = {function = 0x0, arg1 = 0x1, arg2 = 0x0, next = 0x0}}, self_space_ = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7f72c2356598 <std::string::_Rep::_S_empty_rep_storage+24> ""}}, buf_ = 0x7f72adff4760, pinned_ = false}
        s = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x7f72c1df639a "", 0x7f72c1df9d50 "Timeout Acquiring Mutex", 0x7f72c1df9d68 "Timeout waiting to lock key", 0x7f72c1df9dd0 "Failed to acquire lock due to max_num_locks limit", 0x7f72c1df9d84 "No space left on device", 0x7f72c1df9d9c "Deadlock", 
            0x7f72c1df9da5 "Stale file handle", 0x7f72c1df9db7 "Memory limit reached"}}
#8  0x00007f72c198e23d in rocksdb::DB::Get (this=0x7f72be6de000, options=..., key=..., value=0x7f72adff4760) at ./include/rocksdb/db.h:326
No locals.
#9  0x00007f72c1985b28 in crocksdb_get (db=<optimized out>, options=<optimized out>, key=<optimized out>, keylen=<optimized out>, vallen=0x7f72adff47f0, errptr=0x7f72adff47e8) at db/c.cc:765
        result = 0x0
        tmp = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f72c2356598 <std::string::_Rep::_S_empty_rep_storage+24> ""}}
        s = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x7f72c1df639a "", 0x7f72c1df9d50 "Timeout Acquiring Mutex", 0x7f72c1df9d68 "Timeout waiting to lock key", 0x7f72c1df9dd0 "Failed to acquire lock due to max_num_locks limit", 0x7f72c1df9d84 "No space left on device", 0x7f72c1df9d9c "Deadlock", 
            0x7f72c1df9da5 "Stale file handle", 0x7f72c1df9db7 "Memory limit reached"}}
#10 0x00007f72c1981047 in get_opt (self=<optimized out>, key=..., readopts=<optimized out>) at /home/jenkins/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/328fa01/src/rocksdb.rs:473
        val_len_ptr = 0x7f72adff41f0
        val_len = 140130522187049
        key = {data_ptr = 0x7f72ada0e450 "\001\003", length = 11}
        self = <optimized out>
#11 rocksdb::rocksdb::{{impl}}::get (self=0x7f72be6dcf90, key=...) at /home/jenkins/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/328fa01/src/rocksdb.rs:487
        self = 0x7f72be6dcf90
        key = {data_ptr = 0x7f72ada0e450 "\001\003", length = 11}
#12 0x00007f72c16cccaa in tikv::raftstore::store::engine::{{impl}}::get_value (self=<optimized out>, key=...) at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/raftstore/store/engine.rs:268
        self = 0x7f72adff3c80
        key = {data_ptr = 0xffffffffffffffff <Address 0xffffffffffffffff out of bounds>, length = 0}
---Type <return> to continue, or q <return> to quit---
#13 0x00007f72c14b1003 in get_msg<rocksdb::rocksdb::DB,kvproto::raft_serverpb::RegionLocalState> (self=<optimized out>, key=...) at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/raftstore/store/engine.rs:108
        self = 0x7f72adff3c80
        key = {data_ptr = 0x7f72ada0e450 "\001\003", length = 0}
#14 check_msg<tikv::server::transport::ServerTransport,tikv::pd::async::client::RpcClient> (self=<optimized out>, msg=<optimized out>) at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:741
        state_key = <optimized out>
        from_store_id = <optimized out>
        from_epoch = <optimized out>
        region_id = <optimized out>
        msg = 0x7f72adff7940
        self = 0x7f72adffcfb8
#15 tikv::raftstore::store::store::{{impl}}::on_raft_message<tikv::server::transport::ServerTransport,tikv::pd::async::client::RpcClient> (self=0x7f72adffcfb8, msg=...) at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:650
        region_id = 443896551
        self = 0x7f72adffcfb8
        msg = <optimized out>
#16 0x00007f72c13e09b2 in notify<tikv::server::transport::ServerTransport,tikv::pd::async::client::RpcClient> (self=<optimized out>, event_loop=<optimized out>, msg=...) at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:2023
        msg = <optimized out>
#17 notify<tikv::raftstore::store::store::Store<tikv::server::transport::ServerTransport, tikv::pd::async::client::RpcClient>> (cnt=<optimized out>, self=<optimized out>, handler=<optimized out>) at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:350
        cnt = <optimized out>
#18 mio::event_loop::{{impl}}::run_once<tikv::raftstore::store::store::Store<tikv::server::transport::ServerTransport, tikv::pd::async::client::RpcClient>> (self=<optimized out>, handler=<optimized out>, timeout_ms=...) at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:299
        events = <optimized out>
        messages = 1
        timeout_ms = <error reading variable timeout_ms (DWARF-2 expression error: `DW_OP_stack_value' operations must be used either alone or in conjunction with DW_OP_piece or DW_OP_bit_piece.)>
#19 0x00007f72c14c2ad8 in run<tikv::raftstore::store::store::Store<tikv::server::transport::ServerTransport, tikv::pd::async::client::RpcClient>> (self=<optimized out>, handler=<optimized out>) at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:247
        self = 0x7f72adffe050
        handler = 0x7f72adffcfb8
#20 tikv::raftstore::store::store::{{impl}}::run<tikv::server::transport::ServerTransport,tikv::pd::async::client::RpcClient> (self=<optimized out>, event_loop=<optimized out>) at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:434
        rx = <optimized out>
        self = <optimized out>
        event_loop = <optimized out>
#21 0x00007f72c13c753a in {{closure}}<tikv::pd::async::client::RpcClient,tikv::server::transport::ServerTransport> () at /home/jenkins/workspace/build_tikv_master/go/src/github.com/pingcap/tikv/src/server/node.rs:309
        event_loop = <optimized out>
#22 call_once<(),closure> (self=..., _args=<optimized out>) at /checkout/src/libstd/panic.rs:296
No locals.
#23 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (data=<optimized out>) at /checkout/src/libstd/panicking.rs:454
        data = <optimized out>
#24 0x00007f72c1d74bbb in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
No locals.
#25 0x00007f72c1490237 in try<(),std::panic::AssertUnwindSafe<closure>> (f=...) at /checkout/src/libstd/panicking.rs:433
        any_vtable = <error reading variable any_vtable (Cannot access memory at address 0x0)>
        any_data = <error reading variable any_data (Cannot access memory at address 0xffffffffffffffff)>
#26 catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (f=...) at /checkout/src/libstd/panic.rs:361
No locals.
#27 {{closure}}<closure,()> () at /checkout/src/libstd/thread/mod.rs:360
        their_packet = <optimized out>
#28 alloc::boxed::{{impl}}::call_box<(),closure> (self=0x7f72be751000, args=<optimized out>) at /checkout/src/liballoc/boxed.rs:640
        self = 0x7f72be751000
#29 0x00007f72c1d6c575 in call_once<(),()> () at /checkout/src/liballoc/boxed.rs:650
No locals.
#30 start_thread () at /checkout/src/libstd/sys_common/thread.rs:21
No locals.
#31 std::sys::imp::thread::{{impl}}::new::thread_start () at /checkout/src/libstd/sys/unix/thread.rs:84
No locals.
#32 0x00007f72c0a05aa1 in __pthread_initialize_minimal_internal () from /lib64/libpthread.so.0
No symbol table info available.
#33 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by Darren** [comment]
my cluster is now running with these binary combination:

pd-server 2017-06-06 nightly 
tikv-server 2017-07-07 nightly 
pd-server 2017-07-07 nightly 

tikv-server 2017-07-07 nightly  does not core dump so far, so I close the issue for now.
