### ISSUE TITLE
test: failpoints_cases::test_storage::test_storage_1gc failed

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2692]
```
test failpoints_cases::test_storage::test_storage_1gc ... thread 'storage-scheduler::test_storage_1gc' panicked at 'assertion failed: res.is_ok()', tests/failpoints_cases/test_storage.rs:40:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:537
   6: failpoints::failpoints_cases::test_storage::test_storage_1gc::{{closure}}
             at tests/failpoints_cases/test_storage.rs:40
   7: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:817
   9: <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once
             at /checkout/src/liballoc/boxed.rs:837
  10: tikv::storage::txn::scheduler::execute_callback
             at src/storage/txn/scheduler.rs:157
  11: tikv::storage::txn::scheduler::Scheduler::finish_with_err
             at src/storage/txn/scheduler.rs:1155
  12: tikv::storage::txn::scheduler::Scheduler::on_snapshot_finished
             at src/storage/txn/scheduler.rs:1382
  13: tikv::storage::txn::scheduler::Scheduler::run
             at src/storage/txn/scheduler.rs:1521
  14: tikv::storage::Storage::start::{{closure}}
             at src/storage/mod.rs:542
thread 'failpoints_cases::test_storage::test_storage_1gc' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', libcore/result.rs:916:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: failpoints::failpoints_cases::test_storage::test_storage_1gc
             at tests/failpoints_cases/test_storage.rs:61
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1440
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
test test_setup ... ok

failures:

failures:
    failpoints_cases::test_storage::test_storage_1gc

```

**Comment by wentaoxu** [comment]
this test case will success on linux os, and fail on macbook, I will check it.

**Comment by wentaoxu** [comment]
I think it will help to unset `http_proxy` and `https_proxy`.

**Comment by ngaut** [comment]
Is this issue fixed? @wentaoxu

**Comment by wentaoxu** [comment]
Yes, it is already fixed. @ngaut
