### ISSUE TITLE
test: test_scheduler_leader_change_twice failed sometime in CI 

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#2892]
hi, `test_scheduler_leader_change_twice` failed sometime in CI with the following details:
https://circleci.com/gh/pingcap/tikv/9061?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
test failpoints_cases::test_storage::test_scheduler_leader_change_twice ... thread 'failpoints_cases::test_storage::test_scheduler_leader_change_twice' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for Duration { secs: 5, nanos: 0 }")', libcore/result.rs:916:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: <failpoints::raftstore::cluster::Cluster<T>>::query_leader
             at tests/raftstore/cluster.rs:308
  12: <failpoints::raftstore::cluster::Cluster<T>>::leader_of_region
             at tests/raftstore/cluster.rs:346
  13: <failpoints::raftstore::cluster::Cluster<T>>::must_transfer_leader
             at tests/raftstore/cluster.rs:746
  14: failpoints::failpoints_cases::test_storage::test_scheduler_leader_change_twice
             at tests/failpoints_cases/test_storage.rs:117
  15: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1440
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102

```

**Comment by overvenus** [comment]
Closed via #2911
