### ISSUE TITLE
decode_var_u64 attempt to shift left with overflow

### ISSUE THREAD

**Issue by overvenus** [pingcap/tikv#2941]
TiKV: 74287e026ad099f35d3a94c4341ef4f1ab4111c9

```
thread '<unnamed>' panicked at 'attempt to shift left with overflow', /home/pingcap/stn/tikv/src/util/codec/number.rs:183:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: tikv::util::codec::number::NumberDecoder::decode_var_u64
             at ./src/util/codec/number.rs:183
  11: tikv::util::codec::number::NumberDecoder::decode_var_i64
             at ./src/util/codec/number.rs:161
  12: tikv::util::codec::bytes::encoded_compact_len
             at ./src/util/codec/bytes.rs:105
  13: rust_fuzzer_test_input
             at fuzz_targets/codec_bytes.rs:11
  14: libfuzzer_sys::test_input_wrap::{{closure}}
             at /home/pingcap/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4594b1f/src/lib.rs:11
  15: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:479
  16: <unknown>
             at libpanic_abort/lib.rs:38
==53328== ERROR: libFuzzer: deadly signal
    #0 0x564d9761b793 in __sanitizer_print_stack_trace /checkout/src/libcompiler_builtins/compiler-rt/lib/asan/asan_stack.cc:38
    #1 0x564da39c0e2f in fuzzer::Fuzzer::CrashCallback() /home/pingcap/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4594b1f/libfuzzer/FuzzerLoop.cpp:233
    #2 0x564da39c0cef in fuzzer::Fuzzer::StaticCrashSignalCallback() /home/pingcap/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4594b1f/libfuzzer/FuzzerLoop.cpp:206
    #3 0x564da39bcd88 in fuzzer::CrashHandler(int, siginfo_t*, void*) /home/pingcap/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4594b1f/libfuzzer/FuzzerUtilPosix.cpp:36
    #4 0x7fe1b0df25df  (/lib64/libpthread.so.0+0xf5df)
    #5 0x7fe1b083f1f6 in __GI_raise (/lib64/libc.so.6+0x351f6)
    #6 0x7fe1b08408e7 in __GI_abort (/lib64/libc.so.6+0x368e7)
    #7 0x564da39fdbc8 in panic_abort::__rust_start_panic::abort::h04c625c0a3515e3f /checkout/src/libpanic_abort/lib.rs:59
    #8 0x564da39fdbc8 in __rust_start_panic /checkout/src/libpanic_abort/lib.rs:54

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 CopyPart-; base unit: 192274020466459695361874e4e0f90d93919938
0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xfa,0x18,0x32,0xff,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xff,0xff,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xfa,0x18,0x35,0x0,0x0,0x0,0x0,0x0,0x2,0x82,0x0,0x0,0x0,0x3f,0x3f,0x0,0x0,0x8,0x2,0x7a,0x2,0x32,0x3f,0x0,0x0,
\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfa\x182\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfa\x185\x00\x00\x00\x00\x00\x02\x82\x00\x00\x00??\x00\x00\x08\x02z\x022?\x00\x00
artifact_prefix='/home/pingcap/stn/tikv/fuzz/artifacts/codec_bytes/'; Test unit written to /home/pingcap/stn/tikv/fuzz/artifacts/codec_bytes/crash-f1f0d4a55988a81eb40b3416a487858d027ed67d
Base64: ////////////////////////////////////+hgy/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAA////////////////+hg1AAAAAAACggAAAD8/AAAIAnoCMj8AAA==
```

**Comment by BusyJay** [comment]
It's not a bug. The result will be checked at https://github.com/pingcap/tikv/blob/master/src/util/codec/number.rs#L175.

**Comment by siddontang** [comment]
If panic here, means it can't enter the check? @overvenus
