### ISSUE TITLE
test: test failpoints_cases::test_snap::test_generate_snapshot failed 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2957]
```
t ... thread 'failpoints_cases::test_snap::test_generate_snapshot' panicked at 'the directory "/tmp/test_cluster.rpD6cOfGOSRM" should be empty', tests/failpoints_cases/test_snap.rs:242:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: failpoints::failpoints_cases::test_snap::must_empty_dir
             at tests/failpoints_cases/test_snap.rs:242
   8: failpoints::failpoints_cases::test_snap::test_generate_snapshot
             at tests/failpoints_cases/test_snap.rs:220
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1440
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

**Comment by hicqu** [comment]
Seems max wait 1 seconds is not enough here. I will try to increase it to fix this.
