### ISSUE TITLE
test: thread 'raftstore_cases::test_merge::test_node_check_merged_message' panicked

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#3130]
```
thread 'raftstore_cases::test_merge::test_node_check_merged_message' panicked at 'region id: 1011 start_key: "k2" end_key: "k4" region_epoch {conf_ver: 5 version: 9} peers {id: 1012 store_id: 1} peers {id: 1013 store_id: 2} peers {id: 1014 store_id: 3} is still not merged.', tests/raftstore/pd.rs:814:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: integrations::raftstore::pd::TestPdClient::must_merge
             at tests/raftstore/pd.rs:814
   7: integrations::raftstore_cases::test_merge::test_node_check_merged_message
             at tests/raftstore_cases/test_merge.rs:254
   8: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_merge.rs:187
   9: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

**Comment by BusyJay** [comment]
It's caused by disk stall write and new elections, which is expected.
