### ISSUE TITLE
Get region size error

### ISSUE THREAD

**Issue by denghuancong** [pingcap/tikv#3176]
base info : 
tikv: v2.0.1 using docker deployment
-------------------------------------------------
I want to get the size of every region, check the doc,  using the following cmd: 
```
# the db dir
#ls /data/tidb/data/4d224d10-0a81-4ad1-90dc-07293962a643/e5a28660-
48a2-4a8e-a411-45ec70ea08d3/db
total 149548
-rw-r--r-- 1 root root 8293057 Jun  8 15:59 000003.log
-rw-r--r-- 1 root root   21454 May 30 18:03 000013.sst
-rw-r--r-- 1 root root    5136 May 30 18:03 000014.sst
-rw-r--r-- 1 root root    2019 May 30 18:03 000015.sst
-rw-r--r-- 1 root root   29186 May 30 18:03 000016.sst
-rw-r--r-- 1 root root    2017 May 30 18:03 000017.sst
-rw-r--r-- 1 root root    2228 May 30 18:03 000018.sst
-rw-r--r-- 1 root root    1409 May 30 18:03 000019.sst
-rw-r--r-- 1 root root    1819 May 30 18:03 000020.sst
-rw-r--r-- 1 root root      16 May 30 18:03 CURRENT
-rw-r--r-- 1 root root      37 May 30 18:03 IDENTITY
-rw-r--r-- 1 root root       0 May 30 18:03 LOCK
-rw-r--r-- 1 root root    7550 Jun  8 15:57 LOG
-rw-r--r-- 1 root root   41770 May 30 18:03 LOG.old.1528444308548562
-rw-r--r-- 1 root root    7550 Jun  8 15:51 LOG.old.1528444387461234
-rw-r--r-- 1 root root    7550 Jun  8 15:53 LOG.old.1528444403421422
-rw-r--r-- 1 root root    7550 Jun  8 15:53 LOG.old.1528444432541054
-rw-r--r-- 1 root root    7550 Jun  8 15:53 LOG.old.1528444457187281
-rw-r--r-- 1 root root    7550 Jun  8 15:54 LOG.old.1528444541276765
-rw-r--r-- 1 root root    7550 Jun  8 15:55 LOG.old.1528444618649903
-rw-r--r-- 1 root root    7550 Jun  8 15:56 LOG.old.1528444625834124
-rw-r--r-- 1 root root      13 May 30 18:03 MANIFEST-000001
-rw-r--r-- 1 root root    1221 May 30 18:03 MANIFEST-000006
-rw-r--r-- 1 root root    9121 May 30 18:03 OPTIONS-000010
-rw-r--r-- 1 root root   11457 May 30 18:03 OPTIONS-000012

# the cmd :
RUST_BACKTRACE=1 ./tikv-ctl --db /data/tidb/data/4d224d10-0a81-4ad1-90dc-07293962a643/e5a28660-
48a2-4a8e-a411-45ec70ea08d3/db size -r 1

# return the stack :
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "IO error: While lock file: /data/tidb/data/4d224d10-0a81-4ad1-90dc-07293962a643/e5a28660-48a2-4a8e-a411-45ec70ea08d3/db/LOCK: Resource temporarily unavailable"', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:223
             at libstd/panicking.rs:402
   3: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   4: core::panicking::panic_fmt
             at libstd/panicking.rs:325
   5: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   6: tikv_ctl::new_debug_executor
             at /checkout/src/libcore/result.rs:782
             at src/bin/tikv-ctl.rs:96
   7: tikv_ctl::main
             at src/bin/tikv-ctl.rs:1333
   8: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
   9: main
  10: __libc_start_main
  11: <unknown>

```

**Comment by breeswish** [comment]
If you are using tikv-ctl to read a local db, you need to make sure no other RUNNING tikv is using that db. That's why this is called local mode (offline mode). You can use the remote mode (online mode) of tikv-ctl, namely, by supplying `--host` as well.

Also, you can use pd-ctl `region xxx` command to see the *approximate* size of a region online.

**Comment by denghuancong** [comment]
I run the cmd： ./tikv-ctl --host ip:10081 size -r 8 ， it show the following info, but I also don't know about the size of the region used,  Is 60MB or what ?
```
region id: 8
cf default region size: 307
cf write region size: 60
cf lock region size: 0
```

**Comment by breeswish** [comment]
The unit is in bytes. @hicqu Please take a look. Unit "B" is missing from the output when < 1MB.
