### ISSUE TITLE
server panics when restarting after stopped for a few hours

### ISSUE THREAD

**Issue by disksing** [pingcap/tikv#975]
A 3 nodes cluster, stop a node for a few hours then restart. It panics with following log:

```
29048 2016-08-25 14:07:35,936 raft.rs:582 - INFO  - [region 15540] 15541 became follower at term 66
29049 2016-08-25 14:07:35,936 raft.rs:735 - INFO  - [region 2776] 2777 [term: 15] received a MsgHeartbeat message with higher term fr      om 2779 [term: 69]
29050 2016-08-25 14:07:35,936 raft.rs:582 - INFO  - [region 2776] 2777 became follower at term 69
29051 2016-08-25 14:07:36,250 snap.rs:199 - ERROR - failed to apply snap: Other(StringError("missing snap file /data/test/dianle/data/tikv1/snap/rev_5876_7_2263.snap"))!!!
29052 2016-08-25 14:07:36,250 mod.rs:51 - WARN  - handle task Snap apply for 5876 [takes Duration { secs: 1, nanos: 129691607}]
29053 2016-08-25 14:07:36,274 endpoint.rs:176 - ERROR - failed to get snapshot: Request(message: "peer is not leader" not_leader {region_id: 3004 leader {id: 3007 store_id: 6}})
29054 2016-08-25 14:07:36,274 endpoint.rs:176 - ERROR - failed to get snapshot: Request(message: "peer is not leader" not_leader {region_id: 3016 leader {id: 3019 store_id: 6}})
29055 thread 'raftstore-1' panicked at 'applying snapshot to 5876 failed', src/raftstore/store/store.rs:1199
29056 stack backtrace:
29057    1:     0x7fa3e112ef8d - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
29058    2:     0x7fa3e1134fe1 - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
29059    3:     0x7fa3e1133f59 - std::panicking::default_hook::hbbe7fa36a995aca0
29060    4:     0x7fa3e0e7a670 - tikv::util::panic_hook::set_exit_hook::_{{closure}}::hf7e56c7db7debd8a
29061                         at /home/pingcap/src/github.com/pingcap/tikv/src/util/panic_hook.rs:68
29062    5:     0x7fa3e1134597 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
29063    6:     0x7fa3e1134482 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
29064    7:     0x7fa3e11343b0 - std::panicking::begin_panic_fmt::h20f5943904e5791d
29065    8:     0x7fa3e0d07309 - _<tikv..raftstore..store..store..Store<T, C> as mio..handler..Handler>::notify::hbbedf1c7212e20ed
29066                         at /home/pingcap/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:8
29067                         at /home/pingcap/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:1266
29068    9:     0x7fa3e0ceffb0 - _<tikv..raftstore..store..store..Store<T, C>>::run::h07e797b034747ed5
29069                         at /home/pingcap/.cargo/git/checkouts/mio-e79f285e2377d154/master/src/event_loop.rs:366
29070                         at /home/pingcap/.cargo/git/checkouts/mio-e79f285e2377d154/master/src/event_loop.rs:313
29071                         at /home/pingcap/.cargo/git/checkouts/mio-e79f285e2377d154/master/src/event_loop.rs:261
29072                         at /home/pingcap/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:217
29073   10:     0x7fa3e0c66a70 - std::panicking::try::call::hb22bd3c1347e6e52
29074                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:256
29075                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:282
29076   11:     0x7fa3e113cae6 - __rust_maybe_catch_panic
29077   12:     0x7fa3e0cd0f97 - _<F as alloc..boxed..FnBox<A>>::call_box::h23f612000242526e
29078                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
29079                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:245
29080                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:312
29081                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:587
29082   13:     0x7fa3e11328b2 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
29083   14:     0x7fa3df888183 - start_thread
29084   15:     0x7fa3e00a237c - clone
29085   16:                0x0 - <unknown>
```

**Comment by siddontang** [comment]
Hi @hhkbp2, Please help @BusyJay  to solve it.

**Comment by hhkbp2** [comment]
Still have no clue after tracking the handling of the Applying State and snapshot GC and its conditions(truncated index, etc) in the source code. They looks quite solid and there is no timing issue.

**Comment by siddontang** [comment]
we should think how to recover from this panic too.

**Comment by siddontang** [comment]
I think Should add more tests for snapshot applying.
If we really meet this bug (region is applying but snapshot file is missing), how can we recover from it? We can't panic after restart. 

Maybe we can remove all region data, but this may cause another panic later in raft heartbeat, because the leader may keep a matched index and will send it in heartbeat, but now we have nothing, so a panic will happen in raft log `commit_to`.

**Comment by shenli** [comment]
Any update?

**Comment by siddontang** [comment]
Seem no update.
